/***************************************************************************
 * Copyright (c) 2024 Microsoft Corporation
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * SPDX-License-Identifier: MIT
 **************************************************************************/

/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  specification file(s). For more information please refer to the Azure RTOS */
/*  GUIX Studio User Guide, or visit our web site at azure.com/rtos            */
/*                                                                             */
/*  GUIX Studio Revision 6.2.0.1                                               */
/*  Date (dd.mm.yyyy): 31.10.2022   Time (hh:mm): 14:07                        */
/*******************************************************************************/


#ifndef _ALL_WIDGETS_4BPP_SPECIFICATIONS_H_
#define _ALL_WIDGETS_4BPP_SPECIFICATIONS_H_

#include "gx_studio_widget.h"

/* Define widget ids                                                           */

#define ID_LINE_SCREEN 1
#define ID_LINE_WINDOW 2
#define ID_LINE_WIDTH 3
#define ID_WIDTH_DISPLAY 4
#define ID_LINE_ANGLE 5
#define ID_ANGLE_PROMPT 6
#define ID_PATTERN 7
#define ID_ROUNDED 8
#define IDB_NEXT 9
#define ID_RESIZE_SCREEN 10
#define ID_SLIDER_WIDTH 11
#define ID_RADIO_FOOT 12
#define ID_RADIO_FISH 13
#define ID_RADIO_FOOT_ALPHA 14
#define ID_SLIDER_HEIGHT 15
#define ID_HEIGHT_DISPLAY 16
#define ID_IMAGE_CONVERT_SCREEN 17
#define ID_ALPHA 18
#define ID_COMPRESSED 19
#define ID_DITHER 20
#define ID_MENU_SCREEN 21
#define ID_SCROLL_WHEEL_SCREEN 22
#define ID_DAY_WHEEL 23
#define ID_MONTH_WHEEL 24
#define ID_YEAR_WHEEL 25
#define ID_DAY_SELECT 26
#define ID_DAY_INPUT 27
#define ID_ROTATE_SCREEN 28
#define ID_RADIO_APPLE 29
#define ID_SLIDER_ANGLE 30
#define ID_ANGLE_DISPLAY 31
#define ID_DIRECT_ROTATE 32
#define ID_SPRITE_SCREEN 33
#define ID_ALPHA_SLIDER 34
#define ID_BIRD_SPRITE 35
#define ID_SHAPES_SCREEN 36
#define ID_CIRCLE 37
#define ID_ELLIPSE 38
#define ID_ARC 39
#define ID_PIE 40
#define ID_RECTANGLE 41
#define ID_POLYGON 42
#define ID_ANTI_ALIASED 43
#define ID_ROUND_END 44
#define ID_SOLID_FILL 45
#define ID_PIXELMAP_FILL 46
#define ID_RADIUS_SLIDER 47
#define ID_RADIUS_PROMPT 48
#define ID_BRUSH_WIDTH_PROMPT 49
#define ID_BRUSH_WIDTH 50
#define ID_TRANSPARENT 51
#define ID_INDICATOR_SCREEN 52
#define ID_SLIDER_HORIZONTAL 53
#define ID_SLIDER_1 54
#define ID_PIXELMAP_SLIDER_H 55
#define ID_PIXELMAP_SLIDER1 56
#define ID_TEXT_SCREEN 57
#define ID_PROMPT_1 58
#define ID_PROMPT_2 59
#define ID_PROMPT_3 60
#define ID_PROMPT_4 61
#define ID_WINDOW_SCREEN 62
#define ID_HORIZONTAL_SCROLLBAR 63
#define ID_VERTICAL_SCROLLBAR 64
#define ID_VERTICAL_LIST 65
#define ID_DROP_LIST 66
#define ID_BUTTON_SCREEN 67
#define ID_TEXT_BUTTON 68
#define ID_CHECKBOX 69
#define ID_RADIO_BUTTON 70
#define ID_PIXELMAP_BUTTON 71
#define ID_ICON 72
#define ID_ICON_BUTTON 73


/* Define animation ids                                                        */

#define GX_NEXT_ANIMATION_ID 1


/* Define user event ids                                                       */

#define GX_NEXT_USER_EVENT_ID GX_FIRST_USER_EVENT


/* Declare top-level control blocks                                            */

struct LINE_SCREEN_CONTROL_BLOCK : public GX_WINDOW
{
    GX_WINDOW line_screen_line_window;
    GX_PROMPT line_screen_prompt_12;
    GX_SLIDER line_screen_line_width_slider;
    GX_PROMPT line_screen_width_display;
    GX_PROMPT line_screen_prompt_13;
    GX_SLIDER line_screen_line_angle_slider;
    GX_PROMPT line_screen_line_angle;
    GX_CHECKBOX line_screen_pattern_box;
    GX_CHECKBOX line_screen_rounded_box_1;
    GX_TEXT_BUTTON line_screen_next_button_11;
};

struct RESIZE_SCREEN_CONTROL_BLOCK : public GX_WINDOW
{
    GX_PROMPT resize_screen_prompt_16_1;
    GX_SLIDER resize_screen_slider_angle;
    GX_PROMPT resize_screen_prompt_angle;
    GX_WINDOW resize_screen_resize_window;
    GX_RADIO_BUTTON resize_screen_radio_button_9;
    GX_RADIO_BUTTON resize_screen_radio_button_10;
    GX_RADIO_BUTTON resize_screen_radio_button_11;
    GX_PROMPT resize_screen_prompt_17_3;
    GX_PROMPT resize_screen_prompt_18;
    GX_SLIDER resize_screen_slider_angle_1;
    GX_PROMPT resize_screen_prompt_angle_1;
    GX_TEXT_BUTTON resize_screen_next_button_10;
};

struct IMAGE_CONVERT_SCREEN_CONTROL_BLOCK : public GX_WINDOW
{
    GX_WINDOW image_convert_screen_png_to_4bit_gray_win;
    GX_PROMPT image_convert_screen_prompt_17;
    GX_WINDOW image_convert_screen_jpeg_to_4bit_gray_win;
    GX_PROMPT image_convert_screen_prompt_17_1;
    GX_PROMPT image_convert_screen_prompt_17_2;
    GX_TEXT_BUTTON image_convert_screen_next_button_9;
    GX_CHECKBOX image_convert_screen_checkbox_1;
    GX_CHECKBOX image_convert_screen_checkbox_2;
    GX_CHECKBOX image_convert_screen_checkbox_3;
};

struct MENU_SCREEN_CONTROL_BLOCK : public GX_WINDOW
{
    GX_PROMPT menu_screen_title_2;
    GX_PROMPT menu_screen_title_3;
    GX_ACCORDION_MENU menu_screen_one_level_accordion;
    GX_MENU menu_screen_ola_menu_3;
    GX_PROMPT menu_screen_prompt_25_1;
    GX_NUMERIC_PROMPT menu_screen_prompt_26_1;
    GX_MENU menu_screen_ola_menu_4;
    GX_MULTI_LINE_TEXT_VIEW menu_screen_text_view;
    GX_TEXT_BUTTON menu_screen_ola_menu;
    GX_MENU menu_screen_ola_menu_1;
    GX_MENU menu_screen_item;
    GX_MENU menu_screen_item_1;
    GX_ACCORDION_MENU menu_screen_one_level_accordion_2;
    GX_MENU menu_screen_ola_2_menu_4;
    GX_PROMPT menu_screen_prompt_14_2;
    GX_ACCORDION_MENU menu_screen_ola_2_menu_3;
    GX_MENU menu_screen_ola_2_menu;
    GX_PIXELMAP_PROMPT menu_screen_prompt_15_2;
    GX_MENU menu_screen_ola_2_menu_1;
    GX_NUMERIC_PIXELMAP_PROMPT menu_screen_numeric_pixelmap_prompt;
    GX_MENU menu_screen_ola_2_menu_2;
    GX_PROMPT menu_screen_prompt_10_1;
    GX_MULTI_LINE_TEXT_VIEW menu_screen_text_view_3;
    GX_ACCORDION_MENU menu_screen_multi_level_accordion_1;
    GX_MENU menu_screen_mla_menu_5;
    GX_ACCORDION_MENU menu_screen_mla_menu_1_accordion_1;
    GX_MENU menu_screen_mla_menu_3;
    GX_MULTI_LINE_TEXT_VIEW menu_screen_text_view_2;
    GX_MENU menu_screen_mla_menu;
    GX_PROMPT menu_screen_prompt_15_1;
    GX_MENU menu_screen_mla_menu_1;
    GX_ACCORDION_MENU menu_screen_mla_menu_2_accordion_1;
    GX_MENU menu_screen_mla_menu_6;
    GX_ACCORDION_MENU menu_screen_mla_menu_2_1_accordion_1;
    GX_MENU menu_screen_mla_menu_4;
    GX_PROMPT menu_screen_prompt_11_2;
    GX_MENU menu_screen_mla_menu_2;
    GX_PROMPT menu_screen_prompt_12_1;
    GX_MENU menu_screen_mla_menu_2_1;
    GX_ACCORDION_MENU menu_screen_mla_menu_2_2_accordion_1;
    GX_MENU menu_screen_mla_menu_2_4;
    GX_PROMPT menu_screen_prompt_13_1;
    GX_MENU menu_screen_mla_menu_2_3;
    GX_PROMPT menu_screen_prompt_14_1;
    GX_MENU menu_screen_mla_menu_8;
    GX_PROMPT menu_screen_mla_menu_3_item_1;
    GX_PROMPT menu_screen_mla_menu_3_item_2;
    GX_ICON menu_screen_mla_menu_3_icon_1;
    GX_PROMPT menu_screen_title_4;
    GX_TREE_VIEW menu_screen_tree_view;
    GX_MENU menu_screen_tree_menu_3;
    GX_PROMPT menu_screen_tree_menu_6;
    GX_PROMPT menu_screen_tree_menu;
    GX_ICON menu_screen_icon_10;
    GX_MENU menu_screen_tree_menu_1;
    GX_MENU menu_screen_tree_menu_7;
    GX_PROMPT menu_screen_tree_menu_4;
    GX_PROMPT menu_screen_tree_menu_2;
    GX_ICON menu_screen_icon_11;
    GX_MENU menu_screen_tree_menu_2_1;
    GX_MENU menu_screen_tree_menu_2_4;
    GX_PROMPT menu_screen_tree_menu_2_3;
    GX_PROMPT menu_screen_tree_menu_2_2;
    GX_ICON menu_screen_icon_5;
    GX_ICON menu_screen_icon_9;
    GX_ICON menu_screen_icon_6;
    GX_MENU menu_screen_tree_menu_9;
    GX_PROMPT menu_screen_tree_menu_8;
    GX_ICON menu_screen_icon_12;
    GX_SCROLLBAR menu_screen_tree_hscroll_1;
    GX_SCROLLBAR menu_screen_tree_vscroll_1;
    GX_PROMPT menu_screen_prompt_16;
    GX_MENU menu_screen_menu_1;
    GX_PROMPT menu_screen_prompt_10_3;
    GX_ICON menu_screen_icon_8;
    GX_PROMPT menu_screen_title_5;
    GX_TEXT_BUTTON menu_screen_next_button_8;
};

struct SCROLL_WHEEL_SCREEN_CONTROL_BLOCK : public GX_WINDOW
{
};

struct ROTATE_SCREEN_CONTROL_BLOCK : public GX_WINDOW
{
    GX_TEXT_BUTTON rotate_screen_next_button_6;
    GX_PROMPT rotate_screen_prompt_9;
    GX_WINDOW rotate_screen_pixelmap_window;
    GX_RADIO_BUTTON rotate_screen_radio_button_6;
    GX_RADIO_BUTTON rotate_screen_radio_button_7;
    GX_RADIO_BUTTON rotate_screen_radio_button_8;
    GX_SLIDER rotate_screen_slider_3;
    GX_PROMPT rotate_screen_prompt_10;
    GX_CHECKBOX rotate_screen_checkbox;
};

struct SPRITE_SCREEN_CONTROL_BLOCK : public GX_WINDOW
{
    GX_WINDOW sprite_screen_apple_window;
    GX_SLIDER sprite_screen_slider_2;
    GX_TEXT_BUTTON sprite_screen_next_button_5;
    GX_SPRITE sprite_screen_sprite;
    GX_SPRITE sprite_screen_sprite_1;
};

struct SHAPES_SCREEN_CONTROL_BLOCK : public GX_WINDOW
{
    GX_WINDOW shapes_screen_graphics_window;
    GX_TEXT_BUTTON shapes_screen_next_button_4;
    GX_WINDOW shapes_screen_window;
    GX_RADIO_BUTTON shapes_screen_radio_button;
    GX_RADIO_BUTTON shapes_screen_radio_button_1;
    GX_RADIO_BUTTON shapes_screen_radio_button_2;
    GX_RADIO_BUTTON shapes_screen_radio_button_3;
    GX_RADIO_BUTTON shapes_screen_radio_button_4;
    GX_RADIO_BUTTON shapes_screen_radio_button_5;
    GX_PROMPT shapes_screen_prompt;
    GX_CHECKBOX shapes_screen_checkbox_anti_alised;
    GX_CHECKBOX shapes_screen_checkbox_round_end;
    GX_CHECKBOX shapes_screen_checkbox_fill;
    GX_CHECKBOX shapes_screen_checkbox_pixelmap_fill;
    GX_PROMPT shapes_screen_prompt_5;
    GX_PROMPT shapes_screen_prompt_6;
    GX_SLIDER shapes_screen_radius_slider;
    GX_PROMPT shapes_screen_prompt_7;
    GX_PROMPT shapes_screen_prompt_8;
    GX_SLIDER shapes_screen_brush_width_slider;
    GX_WINDOW shapes_screen_window_1;
    GX_CHECKBOX shapes_screen_transparent;
    GX_CHECKBOX shapes_screen_compressed;
};

struct INDICATOR_SCREEN_CONTROL_BLOCK : public GX_WINDOW
{
    GX_SLIDER indicator_screen_slider;
    GX_SLIDER indicator_screen_slider_1;
    GX_PIXELMAP_SLIDER indicator_screen_pixelmap_slider;
    GX_PIXELMAP_SLIDER indicator_screen_pixelmap_slider_1;
    GX_ICON indicator_screen_icon_1;
    GX_ICON indicator_screen_icon_2;
    GX_PROMPT indicator_screen_slider_title;
    GX_TEXT_BUTTON indicator_screen_next_button_3;
    GX_PROGRESS_BAR indicator_screen_progress_bar_1;
    GX_PIXELMAP_SLIDER indicator_screen_pixelmap_slider_2;
    GX_ICON indicator_screen_icon_3;
    GX_ICON indicator_screen_icon_4;
    GX_RADIAL_PROGRESS_BAR indicator_screen_radial_progress_bar_1;
};

struct TEXT_SCREEN_CONTROL_BLOCK : public GX_WINDOW
{
    GX_PROMPT text_screen_prompt_1;
    GX_PROMPT text_screen_prompt_2;
    GX_PROMPT text_screen_prompt_3;
    GX_PIXELMAP_PROMPT text_screen_prompt_4;
    GX_SINGLE_LINE_TEXT_INPUT text_screen_text_input_1;
    GX_MULTI_LINE_TEXT_VIEW text_screen_text_view_1;
    GX_MULTI_LINE_TEXT_INPUT text_screen_text_input_2;
    GX_TEXT_BUTTON text_screen_next_button_2;
    GX_NUMERIC_PIXELMAP_PROMPT text_screen_numeric_pixelmap_prompt_1;
    GX_NUMERIC_PROMPT text_screen_numeric_prompt_1;
    GX_WINDOW text_screen_window_2;
    GX_WINDOW text_screen_window_3;
};

struct WINDOW_SCREEN_CONTROL_BLOCK : public GX_WINDOW
{
    GX_WINDOW window_screen_window_5;
    GX_WINDOW window_screen_window_6;
    GX_WINDOW window_screen_window_8;
    GX_WINDOW window_screen_scroll_frame_1;
    GX_WINDOW window_screen_window_4;
    GX_SCROLLBAR window_screen_hscroll_1;
    GX_SCROLLBAR window_screen_vertical_scroll_1;
    GX_VERTICAL_LIST window_screen_vertical_list;
    GX_TEXT_BUTTON window_screen_button_1;
    GX_TEXT_BUTTON window_screen_button_2;
    GX_TEXT_BUTTON window_screen_button_3;
    GX_TEXT_BUTTON window_screen_button_4;
    GX_PROMPT window_screen_nested_label_1;
    GX_PROMPT window_screen_frame_label_1;
    GX_PROMPT window_screen_vlist_label_1;
    GX_HORIZONTAL_LIST window_screen_horizontal_list_1;
    GX_ICON_BUTTON window_screen_icon_button_1;
    GX_ICON_BUTTON window_screen_icon_button_2;
    GX_ICON_BUTTON window_screen_icon_button_3;
    GX_ICON_BUTTON window_screen_icon_button_4;
    GX_ICON_BUTTON window_screen_icon_button_5;
    GX_PROMPT window_screen_hlist_label_1;
    GX_TEXT_BUTTON window_screen_next_button_1;
    GX_DROP_LIST window_screen_drop_list;
    GX_BUTTON window_screen_button;
    GX_PROMPT window_screen_hlist_label;
};

struct BUTTON_SCREEN_CONTROL_BLOCK : public GX_WINDOW
{
    GX_PROMPT button_screen_title_1;
    GX_BUTTON button_screen_base_button_1;
    GX_TEXT_BUTTON button_screen_text_button_1;
    GX_CHECKBOX button_screen_checkbox1_1;
    GX_RADIO_BUTTON button_screen_radio_button1_1;
    GX_PIXELMAP_BUTTON button_screen_pixelmap_button1_1;
    GX_ICON button_screen_icon;
    GX_ICON_BUTTON button_screen_icon_button_6;
    GX_PROMPT button_screen_button_label_1;
    GX_PROMPT button_screen_radio_label_1;
    GX_PROMPT button_screen_pixbutton_label_1;
    GX_PROMPT button_screen_texbutton_label_1;
    GX_PROMPT button_screen_checkbox_label_1;
    GX_PROMPT button_screen_iconbutton_label_1;
    GX_PROMPT button_screen_icon_label_1;
    GX_TEXT_BUTTON button_screen_next_button;
};


/* extern statically defined control blocks                                    */

#ifndef GUIX_STUDIO_GENERATED_FILE
extern LINE_SCREEN_CONTROL_BLOCK line_screen;
extern RESIZE_SCREEN_CONTROL_BLOCK resize_screen;
extern IMAGE_CONVERT_SCREEN_CONTROL_BLOCK image_convert_screen;
extern MENU_SCREEN_CONTROL_BLOCK menu_screen;
extern ROTATE_SCREEN_CONTROL_BLOCK rotate_screen;
extern SPRITE_SCREEN_CONTROL_BLOCK sprite_screen;
extern SHAPES_SCREEN_CONTROL_BLOCK shapes_screen;
extern INDICATOR_SCREEN_CONTROL_BLOCK indicator_screen;
extern TEXT_SCREEN_CONTROL_BLOCK text_screen;
extern WINDOW_SCREEN_CONTROL_BLOCK window_screen;
extern BUTTON_SCREEN_CONTROL_BLOCK button_screen;
#endif

/* Declare event process functions, draw functions, and callback functions     */

UINT line_screen_event_handler(GX_WINDOW *widget, GX_EVENT *event_ptr);
VOID line_win_draw(GX_WINDOW *widget);
UINT resize_screen_event_handler(GX_WINDOW *widget, GX_EVENT *event_ptr);
VOID resize_window_draw(GX_WINDOW *widget);
UINT image_convert_screen_handler(GX_WINDOW *widget, GX_EVENT *event_ptr);
VOID png_to_4bit_gray_win_draw(GX_WINDOW *widget);
VOID jpeg_to_4bit_gray_win_draw(GX_WINDOW *widget);
UINT next_button_handler(GX_WINDOW *widget, GX_EVENT *event_ptr);
UINT scroll_wheel_screen_event_handler(GX_WINDOW *widget, GX_EVENT *event_ptr);
UINT day_wheel_value_format(GX_NUMERIC_SCROLL_WHEEL *wheel, INT row, GX_STRING *string);
UINT rotate_event_handler(GX_WINDOW *widget, GX_EVENT *event_ptr);
VOID pixelmap_draw(GX_WINDOW *widget);
UINT sprite_event_handler(GX_WINDOW *widget, GX_EVENT *event_ptr);
VOID apple_window_draw(GX_WINDOW *widget);
UINT shapesscreen_event_handler(GX_WINDOW *widget, GX_EVENT *event_ptr);
VOID graphics_draw(GX_WINDOW *widget);
VOID numeric_pixelmap_format_func(GX_NUMERIC_PIXELMAP_PROMPT *, INT);
VOID format_func(GX_NUMERIC_PROMPT *, INT);
UINT window_screen_event_handler(GX_WINDOW *widget, GX_EVENT *event_ptr);
VOID drop_list_row_create(GX_VERTICAL_LIST *, GX_WIDGET *, INT);


/* Declare Studio-generated functions for creating top-level widgets           */

UINT gx_studio_named_widget_create(char *name, GX_WIDGET *parent, GX_WIDGET **new_widget);
UINT gx_studio_display_configure(USHORT display, UINT (*driver)(GX_DISPLAY *), GX_UBYTE language, USHORT theme, GX_WINDOW_ROOT **return_root);

#endif                                       /* sentry                         */
