/***************************************************************************
 * Copyright (c) 2024 Microsoft Corporation
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * SPDX-License-Identifier: MIT
 **************************************************************************/

/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  specification file(s). For more information please refer to the Azure RTOS */
/*  GUIX Studio User Guide, or visit our web site at azure.com/rtos            */
/*                                                                             */
/*  GUIX Studio Revision 6.1.12.0                                              */
/*  Date (dd.mm.yyyy): 25. 8.2022   Time (hh:mm): 18:43                        */
/*******************************************************************************/


#define GUIX_STUDIO_GENERATED_FILE
#include <stddef.h>
#include "demo_guix_binres_resources.h"
#include "demo_guix_binres_specifications.h"

SIMPLE_WINDOW_CONTROL_BLOCK simple_window;
GX_DISPLAY main_display_control_block;
GX_WINDOW_ROOT main_display_root_window;
GX_CANVAS  main_display_canvas_control_block;

GX_STUDIO_DISPLAY_INFO demo_guix_binres_display_table[1] =
{
    {
    "main_display",
    "main_display_canvas",
    GX_NULL,
    GX_NULL,
    0,
    0,
    0,
    640,                                     /* x resolution                   */
    480,                                     /* y resolution                   */
    &main_display_control_block,
    &main_display_canvas_control_block,
    &main_display_root_window,
    GX_NULL,                                 /* canvas memory area             */
    614400,                                  /* canvas memory size in bytes    */
    GX_SCREEN_ROTATION_NONE                  /* rotation angle                 */
    }
};


GX_WINDOW_PROPERTIES simple_window_properties =
{
    0                                        /* wallpaper pixelmap id          */
};
GX_PIXELMAP_BUTTON_PROPERTIES simple_window_simple_button_properties =
{
    GX_PIXELMAP_ID_BUTTON,                   /* normal pixelmap id             */
    GX_PIXELMAP_ID_BUTTON_ACTIVE,            /* selected pixelmap id           */
    0                                        /* disabled pixelmap id           */
};
GX_PROMPT_PROPERTIES simple_window_button_text_properties =
{
    GX_STRING_ID_STRING_22,                  /* string id                      */
    GX_FONT_ID_SYSTEM,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected text color            */
    GX_COLOR_ID_TEXT                         /* disabled text color            */
};
GX_WINDOW_PROPERTIES simple_window_scroll_frame_properties =
{
    0                                        /* wallpaper pixelmap id          */
};
GX_WINDOW_PROPERTIES simple_window_window_properties =
{
    GX_PIXELMAP_ID_RED_APPLE                 /* wallpaper pixelmap id          */
};
GX_SCROLLBAR_APPEARANCE  simple_window_vertical_scroll_properties =
{
    20,                                      /* scroll width                   */
    12,                                      /* thumb width                    */
    20,                                      /* thumb travel min               */
    20,                                      /* thumb travel max               */
    4,                                       /* thumb border style             */
    0,                                       /* scroll fill pixelmap           */
    0,                                       /* scroll thumb pixelmap          */
    0,                                       /* scroll up pixelmap             */
    0,                                       /* scroll down pixelmap           */
    GX_COLOR_ID_ORANGE,                      /* scroll thumb color             */
    GX_COLOR_ID_SCROLL_BUTTON,               /* scroll thumb border color      */
    GX_COLOR_ID_BLUE,                        /* scroll button color            */
};
GX_SCROLLBAR_APPEARANCE  simple_window_hscroll_properties =
{
    20,                                      /* scroll width                   */
    10,                                      /* thumb width                    */
    2,                                       /* thumb travel min               */
    2,                                       /* thumb travel max               */
    4,                                       /* thumb border style             */
    0,                                       /* scroll fill pixelmap           */
    0,                                       /* scroll thumb pixelmap          */
    0,                                       /* scroll up pixelmap             */
    0,                                       /* scroll down pixelmap           */
    GX_COLOR_ID_ORANGE,                      /* scroll thumb color             */
    GX_COLOR_ID_SCROLL_BUTTON,               /* scroll thumb border color      */
    GX_COLOR_ID_BTN_UPPER,                   /* scroll button color            */
};
GX_WINDOW_PROPERTIES simple_window_window_theme_setting_properties =
{
    0                                        /* wallpaper pixelmap id          */
};
GX_RADIO_BUTTON_PROPERTIES simple_window_radio_button_theme_1_properties =
{
    GX_STRING_ID_STRING_12,                  /* string id                      */
    GX_FONT_ID_SYSTEM,                       /* font id                        */
    GX_COLOR_ID_TEXT_COLOR,                  /* normal text color              */
    GX_COLOR_ID_TEXT_COLOR,                  /* selected text color            */
    GX_COLOR_ID_TEXT_COLOR,                  /* disabled text color            */
    0,                                       /* off pixelmap id                */
    0,                                       /* on pixelmap id                 */
    0,                                       /* off disabled pixelmap id       */
    0                                        /* on disabled pixelmap id        */
};
GX_PROMPT_PROPERTIES simple_window_prompt_Themes_properties =
{
    GX_STRING_ID_STRING_11,                  /* string id                      */
    GX_FONT_ID_PROMPT,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected text color            */
    GX_COLOR_ID_TEXT                         /* disabled text color            */
};
GX_RADIO_BUTTON_PROPERTIES simple_window_radio_button_theme_2_properties =
{
    GX_STRING_ID_STRING_13,                  /* string id                      */
    GX_FONT_ID_SYSTEM,                       /* font id                        */
    GX_COLOR_ID_TEXT_COLOR,                  /* normal text color              */
    GX_COLOR_ID_TEXT_COLOR,                  /* selected text color            */
    GX_COLOR_ID_TEXT_COLOR,                  /* disabled text color            */
    0,                                       /* off pixelmap id                */
    0,                                       /* on pixelmap id                 */
    0,                                       /* off disabled pixelmap id       */
    0                                        /* on disabled pixelmap id        */
};
GX_WINDOW_PROPERTIES simple_window_window_language_setting_properties =
{
    0                                        /* wallpaper pixelmap id          */
};
GX_RADIO_BUTTON_PROPERTIES simple_window_radio_button_English_properties =
{
    GX_STRING_ID_STRING_1,                   /* string id                      */
    GX_FONT_ID_SYSTEM,                       /* font id                        */
    GX_COLOR_ID_TEXT_COLOR,                  /* normal text color              */
    GX_COLOR_ID_TEXT_COLOR,                  /* selected text color            */
    GX_COLOR_ID_TEXT_COLOR,                  /* disabled text color            */
    0,                                       /* off pixelmap id                */
    0,                                       /* on pixelmap id                 */
    0,                                       /* off disabled pixelmap id       */
    0                                        /* on disabled pixelmap id        */
};
GX_PROMPT_PROPERTIES simple_window_prompt_Languages_properties =
{
    GX_STRING_ID_STRING_17,                  /* string id                      */
    GX_FONT_ID_PROMPT,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected text color            */
    GX_COLOR_ID_TEXT                         /* disabled text color            */
};
GX_RADIO_BUTTON_PROPERTIES simple_window_radio_button_Chinese_properties =
{
    GX_STRING_ID_STRING_3,                   /* string id                      */
    GX_FONT_ID_SYSTEM,                       /* font id                        */
    GX_COLOR_ID_TEXT_COLOR,                  /* normal text color              */
    GX_COLOR_ID_TEXT_COLOR,                  /* selected text color            */
    GX_COLOR_ID_TEXT_COLOR,                  /* disabled text color            */
    0,                                       /* off pixelmap id                */
    0,                                       /* on pixelmap id                 */
    0,                                       /* off disabled pixelmap id       */
    0                                        /* on disabled pixelmap id        */
};
GX_ICON_PROPERTIES simple_window_logo_properties =
{
    GX_PIXELMAP_ID_MS_AZURE_LOGO_SMALL,      /* normal pixelmap id             */
    0                                        /* selected pixelmap id           */
};

GX_CONST GX_STUDIO_WIDGET simple_window_button_text_define =
{
    "button_text",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_TEXT_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_WIDGET_FILL,                 /* disabled color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {441, 134, 526, 151},                    /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(SIMPLE_WINDOW_CONTROL_BLOCK, simple_window_button_text), /* control block */
    (void *) &simple_window_button_text_properties /* extended properties      */
};

GX_CONST GX_STUDIO_WIDGET simple_window_hscroll_define =
{
    "hscroll",
    GX_TYPE_HORIZONTAL_SCROLL,               /* widget type                    */
    ID_HORIZONTAL_SCROLLBAR,                 /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_TILE_BACKGROUND|GX_SCROLLBAR_RELATIVE_THUMB|GX_SCROLLBAR_HORIZONTAL,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_SCROLLBAR),                    /* control block size             */
    GX_COLOR_ID_ORANGE,                      /* normal color id                */
    GX_COLOR_ID_SCROLL_FILL,                 /* selected color id              */
    GX_COLOR_ID_ORANGE,                      /* disabled color id              */
    gx_studio_horizontal_scrollbar_create,     /* create function              */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {161, 187, 350, 206},                    /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(SIMPLE_WINDOW_CONTROL_BLOCK, simple_window_hscroll), /* control block */
    (void *) &simple_window_hscroll_properties /* extended properties          */
};

GX_CONST GX_STUDIO_WIDGET simple_window_vertical_scroll_define =
{
    "vertical_scroll",
    GX_TYPE_VERTICAL_SCROLL,                 /* widget type                    */
    ID_VERTICAL_SCROLLBAR,                   /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_THIN|GX_SCROLLBAR_RELATIVE_THUMB|GX_SCROLLBAR_END_BUTTONS|GX_SCROLLBAR_VERTICAL,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_SCROLLBAR),                    /* control block size             */
    GX_COLOR_ID_SCROLL_FILL,                 /* normal color id                */
    GX_COLOR_ID_SCROLL_FILL,                 /* selected color id              */
    GX_COLOR_ID_SCROLL_FILL,                 /* disabled color id              */
    gx_studio_vertical_scrollbar_create,     /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {351, 73, 370, 206},                     /* widget size                    */
    &simple_window_hscroll_define,           /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(SIMPLE_WINDOW_CONTROL_BLOCK, simple_window_vertical_scroll), /* control block */
    (void *) &simple_window_vertical_scroll_properties /* extended properties  */
};

GX_CONST GX_STUDIO_WIDGET simple_window_window_define =
{
    "window",
    GX_TYPE_WINDOW,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_THIN,                    /* style flags                    */
    0,                                       /* status flags                   */
    sizeof(GX_WINDOW),                       /* control block size             */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_WINDOW_FILL,                 /* selected color id              */
    GX_COLOR_ID_WINDOW_FILL,                 /* disabled color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {160, 72, 354, 338},                     /* widget size                    */
    &simple_window_vertical_scroll_define,   /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(SIMPLE_WINDOW_CONTROL_BLOCK, simple_window_window), /* control block */
    (void *) &simple_window_window_properties /* extended properties           */
};

GX_CONST GX_STUDIO_WIDGET simple_window_radio_button_theme_2_define =
{
    "radio_button_theme_2",
    GX_TYPE_RADIO_BUTTON,                    /* widget type                    */
    ID_THEME_2,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_BUTTON_RADIO|GX_STYLE_TEXT_LEFT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_RADIO_BUTTON),                 /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_LOWER,                   /* disabled color id              */
    gx_studio_radio_button_create,           /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {164, 345, 261, 374},                    /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(SIMPLE_WINDOW_CONTROL_BLOCK, simple_window_radio_button_theme_2), /* control block */
    (void *) &simple_window_radio_button_theme_2_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET simple_window_prompt_Themes_define =
{
    "prompt_Themes",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_TEXT_CENTER,   /* style flags */
    0,                                       /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_WIDGET_FILL,                 /* disabled color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {159, 271, 238, 294},                    /* widget size                    */
    &simple_window_radio_button_theme_2_define, /* next widget definition      */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(SIMPLE_WINDOW_CONTROL_BLOCK, simple_window_prompt_Themes), /* control block */
    (void *) &simple_window_prompt_Themes_properties /* extended properties    */
};

GX_CONST GX_STUDIO_WIDGET simple_window_radio_button_theme_1_define =
{
    "radio_button_theme_1",
    GX_TYPE_RADIO_BUTTON,                    /* widget type                    */
    ID_THEME_1,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_BUTTON_PUSHED|GX_STYLE_BUTTON_RADIO|GX_STYLE_TEXT_LEFT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_RADIO_BUTTON),                 /* control block size             */
    GX_COLOR_ID_BTN_UPPER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_UPPER,                   /* disabled color id              */
    gx_studio_radio_button_create,           /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {164, 306, 261, 333},                    /* widget size                    */
    &simple_window_prompt_Themes_define,     /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(SIMPLE_WINDOW_CONTROL_BLOCK, simple_window_radio_button_theme_1), /* control block */
    (void *) &simple_window_radio_button_theme_1_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET simple_window_radio_button_Chinese_define =
{
    "radio_button_Chinese",
    GX_TYPE_RADIO_BUTTON,                    /* widget type                    */
    ID_SPANISH,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_BUTTON_RADIO|GX_STYLE_TEXT_LEFT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_RADIO_BUTTON),                 /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_LOWER,                   /* disabled color id              */
    gx_studio_radio_button_create,           /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {351, 343, 477, 371},                    /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(SIMPLE_WINDOW_CONTROL_BLOCK, simple_window_radio_button_Chinese), /* control block */
    (void *) &simple_window_radio_button_Chinese_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET simple_window_prompt_Languages_define =
{
    "prompt_Languages",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_TEXT_CENTER,   /* style flags */
    0,                                       /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_WIDGET_FILL,                 /* disabled color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {346, 270, 458, 293},                    /* widget size                    */
    &simple_window_radio_button_Chinese_define, /* next widget definition      */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(SIMPLE_WINDOW_CONTROL_BLOCK, simple_window_prompt_Languages), /* control block */
    (void *) &simple_window_prompt_Languages_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET simple_window_radio_button_English_define =
{
    "radio_button_English",
    GX_TYPE_RADIO_BUTTON,                    /* widget type                    */
    ID_ENGLISH,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_BUTTON_PUSHED|GX_STYLE_BUTTON_RADIO|GX_STYLE_TEXT_LEFT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_RADIO_BUTTON),                 /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_LOWER,                   /* disabled color id              */
    gx_studio_radio_button_create,           /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {351, 305, 477, 333},                    /* widget size                    */
    &simple_window_prompt_Languages_define,  /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(SIMPLE_WINDOW_CONTROL_BLOCK, simple_window_radio_button_English), /* control block */
    (void *) &simple_window_radio_button_English_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET simple_window_logo_define =
{
    "logo",
    GX_TYPE_ICON,                            /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_HALIGN_LEFT|GX_STYLE_VALIGN_TOP,   /* style flags */
    0,                                       /* status flags                   */
    sizeof(GX_ICON),                         /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_WIDGET_FILL,                 /* disabled color id              */
    gx_studio_icon_create,                   /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {15, 15, 203, 44},                       /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(SIMPLE_WINDOW_CONTROL_BLOCK, simple_window_logo), /* control block */
    (void *) &simple_window_logo_properties  /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET simple_window_window_language_setting_define =
{
    "window_language_setting",
    GX_TYPE_WINDOW,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE,                    /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_WINDOW),                       /* control block size             */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_WINDOW_FILL,                 /* selected color id              */
    GX_COLOR_ID_WINDOW_FILL,                 /* disabled color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {337, 256, 492, 387},                    /* widget size                    */
    &simple_window_logo_define,              /* next widget definition         */
    &simple_window_radio_button_English_define, /* child widget definition     */
    offsetof(SIMPLE_WINDOW_CONTROL_BLOCK, simple_window_window_language_setting), /* control block */
    (void *) &simple_window_window_language_setting_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET simple_window_window_theme_setting_define =
{
    "window_theme_setting",
    GX_TYPE_WINDOW,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE,                    /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_WINDOW),                       /* control block size             */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_WINDOW_FILL,                 /* selected color id              */
    GX_COLOR_ID_WINDOW_FILL,                 /* disabled color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {150, 257, 318, 385},                    /* widget size                    */
    &simple_window_window_language_setting_define, /* next widget definition   */
    &simple_window_radio_button_theme_1_define, /* child widget definition     */
    offsetof(SIMPLE_WINDOW_CONTROL_BLOCK, simple_window_window_theme_setting), /* control block */
    (void *) &simple_window_window_theme_setting_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET simple_window_scroll_frame_define =
{
    "scroll_frame",
    GX_TYPE_WINDOW,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_THIN,                    /* style flags                    */
    0,                                       /* status flags                   */
    sizeof(GX_WINDOW),                       /* control block size             */
    GX_COLOR_ID_SCROLL_FILL,                 /* normal color id                */
    GX_COLOR_ID_SCROLL_FILL,                 /* selected color id              */
    GX_COLOR_ID_SCROLL_FILL,                 /* disabled color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {160, 72, 371, 207},                     /* widget size                    */
    &simple_window_window_theme_setting_define, /* next widget definition      */
    &simple_window_window_define,            /* child widget definition        */
    offsetof(SIMPLE_WINDOW_CONTROL_BLOCK, simple_window_scroll_frame), /* control block */
    (void *) &simple_window_scroll_frame_properties /* extended properties     */
};

GX_CONST GX_STUDIO_WIDGET simple_window_simple_button_define =
{
    "simple_button",
    GX_TYPE_PIXELMAP_BUTTON,                 /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PIXELMAP_BUTTON),              /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_LOWER,                   /* disabled color id              */
    gx_studio_pixelmap_button_create,        /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {414, 121, 553, 164},                    /* widget size                    */
    &simple_window_scroll_frame_define,      /* next widget definition         */
    &simple_window_button_text_define,       /* child widget definition        */
    offsetof(SIMPLE_WINDOW_CONTROL_BLOCK, simple_window_simple_button), /* control block */
    (void *) &simple_window_simple_button_properties /* extended properties    */
};

GX_CONST GX_STUDIO_WIDGET simple_window_define =
{
    "simple_window",
    GX_TYPE_WINDOW,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE,                    /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(SIMPLE_WINDOW_CONTROL_BLOCK),     /* control block size             */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_WINDOW_FILL,                 /* selected color id              */
    GX_COLOR_ID_WINDOW_FILL,                 /* disabled color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    (UINT (*)(GX_WIDGET *, GX_EVENT *)) simple_window_event_handler, /* event function override */
    {0, 0, 639, 479},                        /* widget size                    */
    GX_NULL,                                 /* next widget                    */
    &simple_window_simple_button_define,     /* child widget                   */
    0,                                       /* control block                  */
    (void *) &simple_window_properties       /* extended properties            */
};
GX_CONST GX_STUDIO_WIDGET_ENTRY demo_guix_binres_widget_table[] =
{
    { &simple_window_define, (GX_WIDGET *) &simple_window },
    {GX_NULL, GX_NULL}
};

UINT gx_studio_named_widget_create(char *name, GX_WIDGET *parent, GX_WIDGET **new_widget)
{
    return gx_studio_named_widget_create_from_table(name, parent, new_widget, demo_guix_binres_widget_table);
}

UINT gx_studio_display_configure(USHORT display, UINT (*driver)(GX_DISPLAY *),
    GX_UBYTE language, USHORT theme, GX_WINDOW_ROOT **return_root)
{
    GX_STUDIO_DISPLAY_INFO *display_info = &demo_guix_binres_display_table[display];
    return gx_studio_display_config(display_info, driver, language, theme, return_root);
}
#undef GUIX_STUDIO_GENERATED_FILE
