/***************************************************************************
 * Copyright (c) 2024 Microsoft Corporation
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * SPDX-License-Identifier: MIT
 **************************************************************************/

/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  specification file(s). For more information please refer to the Azure RTOS */
/*  GUIX Studio User Guide, or visit our web site at azure.com/rtos            */
/*                                                                             */
/*  GUIX Studio Revision 6.2.0.1                                               */
/*  Date (dd.mm.yyyy): 31.10.2022   Time (hh:mm): 14:11                        */
/*******************************************************************************/


#define GUIX_STUDIO_GENERATED_FILE
#include <stddef.h>
#include "screen_drag_animation_with_block_move_resources.h"
#include "screen_drag_animation_with_block_move_specifications.h"

V_MENU_WINDOW_3_CONTROL_BLOCK v_menu_window_3;
V_MENU_WINDOW_2_CONTROL_BLOCK v_menu_window_2;
H_MENU_WINDOW_2_CONTROL_BLOCK h_menu_window_2;
H_MENU_WINDOW_3_CONTROL_BLOCK h_menu_window_3;
MAIN_SCREEN_CONTROL_BLOCK main_screen;
GX_DISPLAY display_1_control_block;
GX_WINDOW_ROOT display_1_root_window;
GX_CANVAS  display_1_canvas_control_block;
ULONG      display_1_canvas_memory[307200];

extern GX_CONST GX_THEME *display_1_theme_table[];
extern GX_CONST GX_STRING *display_1_language_table[];

GX_STUDIO_DISPLAY_INFO screen_drag_animation_with_block_move_display_table[1] =
{
    {
    "display_1",
    "display_1_canvas",
    display_1_theme_table,
    display_1_language_table,
    DISPLAY_1_THEME_TABLE_SIZE,
    DISPLAY_1_LANGUAGE_TABLE_SIZE,
    DISPLAY_1_STRING_TABLE_SIZE,
    640,                                     /* x resolution                   */
    480,                                     /* y resolution                   */
    &display_1_control_block,
    &display_1_canvas_control_block,
    &display_1_root_window,
    display_1_canvas_memory,                 /* canvas memory area             */
    1228800,                                 /* canvas memory size in bytes    */
    0                                        /* rotation angle                 */
    }
};


GX_WINDOW_PROPERTIES v_menu_window_3_properties =
{
    0                                        /* wallpaper pixelmap id          */
};
GX_PIXELMAP_BUTTON_PROPERTIES v_menu_window_3_message_3_properties =
{
    GX_PIXELMAP_ID_MAP_ON,                   /* normal pixelmap id             */
    GX_PIXELMAP_ID_MAP_PUSHED,               /* selected pixelmap id           */
    0                                        /* disabled pixelmap id           */
};
GX_PIXELMAP_BUTTON_PROPERTIES v_menu_window_3_weather_3_properties =
{
    GX_PIXELMAP_ID_SETTINGS_ON,              /* normal pixelmap id             */
    GX_PIXELMAP_ID_SETTINGS_PUSHED,          /* selected pixelmap id           */
    0                                        /* disabled pixelmap id           */
};
GX_PIXELMAP_BUTTON_PROPERTIES v_menu_window_3_message_properties =
{
    GX_PIXELMAP_ID_MAP_ON,                   /* normal pixelmap id             */
    GX_PIXELMAP_ID_MAP_PUSHED,               /* selected pixelmap id           */
    0                                        /* disabled pixelmap id           */
};
GX_PIXELMAP_BUTTON_PROPERTIES v_menu_window_3_weather_properties =
{
    GX_PIXELMAP_ID_SETTINGS_ON,              /* normal pixelmap id             */
    GX_PIXELMAP_ID_SETTINGS_PUSHED,          /* selected pixelmap id           */
    0                                        /* disabled pixelmap id           */
};

GX_CONST GX_STUDIO_WIDGET v_menu_window_3_weather_define =
{
    "weather",
    GX_TYPE_PIXELMAP_BUTTON,                 /* widget type                    */
    ID_WEATHER,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PIXELMAP_BUTTON),              /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_LOWER,                   /* disabled color id              */
    gx_studio_pixelmap_button_create,        /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {10, 188, 64, 240},                      /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */
    offsetof(V_MENU_WINDOW_3_CONTROL_BLOCK, v_menu_window_3_weather), /* control block */
    (void *) &v_menu_window_3_weather_properties /* extended properties        */
};

GX_CONST GX_STUDIO_WIDGET v_menu_window_3_message_define =
{
    "message",
    GX_TYPE_PIXELMAP_BUTTON,                 /* widget type                    */
    ID_MESSAGE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PIXELMAP_BUTTON),              /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_LOWER,                   /* disabled color id              */
    gx_studio_pixelmap_button_create,        /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {10, 129, 64, 181},                      /* widget size                    */
    &v_menu_window_3_weather_define,         /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */
    offsetof(V_MENU_WINDOW_3_CONTROL_BLOCK, v_menu_window_3_message), /* control block */
    (void *) &v_menu_window_3_message_properties /* extended properties        */
};

GX_CONST GX_STUDIO_WIDGET v_menu_window_3_weather_3_define =
{
    "weather_3",
    GX_TYPE_PIXELMAP_BUTTON,                 /* widget type                    */
    ID_WEATHER,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PIXELMAP_BUTTON),              /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_LOWER,                   /* disabled color id              */
    gx_studio_pixelmap_button_create,        /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {10, 69, 64, 121},                       /* widget size                    */
    &v_menu_window_3_message_define,         /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */
    offsetof(V_MENU_WINDOW_3_CONTROL_BLOCK, v_menu_window_3_weather_3), /* control block */
    (void *) &v_menu_window_3_weather_3_properties /* extended properties      */
};

GX_CONST GX_STUDIO_WIDGET v_menu_window_3_message_3_define =
{
    "message_3",
    GX_TYPE_PIXELMAP_BUTTON,                 /* widget type                    */
    ID_MESSAGE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PIXELMAP_BUTTON),              /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_LOWER,                   /* disabled color id              */
    gx_studio_pixelmap_button_create,        /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {10, 9, 64, 61},                         /* widget size                    */
    &v_menu_window_3_weather_3_define,       /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */
    offsetof(V_MENU_WINDOW_3_CONTROL_BLOCK, v_menu_window_3_message_3), /* control block */
    (void *) &v_menu_window_3_message_3_properties /* extended properties      */
};

GX_CONST GX_STUDIO_WIDGET v_menu_window_3_define =
{
    "v_menu_window_3",
    GX_TYPE_WINDOW,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT,   /* style flags                */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(V_MENU_WINDOW_3_CONTROL_BLOCK),   /* control block size             */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_WINDOW_FILL,                 /* selected color id              */
    GX_COLOR_ID_WINDOW_FILL,                 /* disabled color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {0, 0, 77, 247},                         /* widget size                    */
    GX_NULL,                                 /* next widget                    */
    &v_menu_window_3_message_3_define,       /* child widget                   */
    0,                                       /* control block                  */
    (void *) &v_menu_window_3_properties     /* extended properties            */
};
GX_WINDOW_PROPERTIES v_menu_window_2_properties =
{
    0                                        /* wallpaper pixelmap id          */
};
GX_PIXELMAP_BUTTON_PROPERTIES v_menu_window_2_message_2_properties =
{
    GX_PIXELMAP_ID_GAMES_ON,                 /* normal pixelmap id             */
    GX_PIXELMAP_ID_GAMES_PUSHED,             /* selected pixelmap id           */
    0                                        /* disabled pixelmap id           */
};
GX_PIXELMAP_BUTTON_PROPERTIES v_menu_window_2_weather_2_properties =
{
    GX_PIXELMAP_ID_CLOCK_ON,                 /* normal pixelmap id             */
    GX_PIXELMAP_ID_CLOCK_PUSHED,             /* selected pixelmap id           */
    0                                        /* disabled pixelmap id           */
};
GX_PIXELMAP_BUTTON_PROPERTIES v_menu_window_2_calculator_2_properties =
{
    GX_PIXELMAP_ID_CONTACTS_ON,              /* normal pixelmap id             */
    GX_PIXELMAP_ID_CONTACTS_PUSHED,          /* selected pixelmap id           */
    0                                        /* disabled pixelmap id           */
};
GX_PIXELMAP_BUTTON_PROPERTIES v_menu_window_2_healthy_2_properties =
{
    GX_PIXELMAP_ID_ABOUT_ON,                 /* normal pixelmap id             */
    GX_PIXELMAP_ID_ABOUT_PUSHED,             /* selected pixelmap id           */
    0                                        /* disabled pixelmap id           */
};

GX_CONST GX_STUDIO_WIDGET v_menu_window_2_healthy_2_define =
{
    "healthy_2",
    GX_TYPE_PIXELMAP_BUTTON,                 /* widget type                    */
    ID_HEALTHY,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PIXELMAP_BUTTON),              /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_LOWER,                   /* disabled color id              */
    gx_studio_pixelmap_button_create,        /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {10, 189, 64, 241},                      /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */
    offsetof(V_MENU_WINDOW_2_CONTROL_BLOCK, v_menu_window_2_healthy_2), /* control block */
    (void *) &v_menu_window_2_healthy_2_properties /* extended properties      */
};

GX_CONST GX_STUDIO_WIDGET v_menu_window_2_calculator_2_define =
{
    "calculator_2",
    GX_TYPE_PIXELMAP_BUTTON,                 /* widget type                    */
    ID_CALCULATOR,                           /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PIXELMAP_BUTTON),              /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_LOWER,                   /* disabled color id              */
    gx_studio_pixelmap_button_create,        /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {10, 129, 64, 181},                      /* widget size                    */
    &v_menu_window_2_healthy_2_define,       /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */
    offsetof(V_MENU_WINDOW_2_CONTROL_BLOCK, v_menu_window_2_calculator_2), /* control block */
    (void *) &v_menu_window_2_calculator_2_properties /* extended properties   */
};

GX_CONST GX_STUDIO_WIDGET v_menu_window_2_weather_2_define =
{
    "weather_2",
    GX_TYPE_PIXELMAP_BUTTON,                 /* widget type                    */
    ID_WEATHER,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PIXELMAP_BUTTON),              /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_LOWER,                   /* disabled color id              */
    gx_studio_pixelmap_button_create,        /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {10, 69, 64, 121},                       /* widget size                    */
    &v_menu_window_2_calculator_2_define,    /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */
    offsetof(V_MENU_WINDOW_2_CONTROL_BLOCK, v_menu_window_2_weather_2), /* control block */
    (void *) &v_menu_window_2_weather_2_properties /* extended properties      */
};

GX_CONST GX_STUDIO_WIDGET v_menu_window_2_message_2_define =
{
    "message_2",
    GX_TYPE_PIXELMAP_BUTTON,                 /* widget type                    */
    ID_MESSAGE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PIXELMAP_BUTTON),              /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_LOWER,                   /* disabled color id              */
    gx_studio_pixelmap_button_create,        /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {10, 9, 64, 61},                         /* widget size                    */
    &v_menu_window_2_weather_2_define,       /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */
    offsetof(V_MENU_WINDOW_2_CONTROL_BLOCK, v_menu_window_2_message_2), /* control block */
    (void *) &v_menu_window_2_message_2_properties /* extended properties      */
};

GX_CONST GX_STUDIO_WIDGET v_menu_window_2_define =
{
    "v_menu_window_2",
    GX_TYPE_WINDOW,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT,   /* style flags                */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(V_MENU_WINDOW_2_CONTROL_BLOCK),   /* control block size             */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_WINDOW_FILL,                 /* selected color id              */
    GX_COLOR_ID_WINDOW_FILL,                 /* disabled color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {0, 0, 77, 247},                         /* widget size                    */
    GX_NULL,                                 /* next widget                    */
    &v_menu_window_2_message_2_define,       /* child widget                   */
    0,                                       /* control block                  */
    (void *) &v_menu_window_2_properties     /* extended properties            */
};
GX_WINDOW_PROPERTIES h_menu_window_2_properties =
{
    0                                        /* wallpaper pixelmap id          */
};
GX_PIXELMAP_BUTTON_PROPERTIES h_menu_window_2_games_properties =
{
    GX_PIXELMAP_ID_GAMES_ON,                 /* normal pixelmap id             */
    GX_PIXELMAP_ID_GAMES_PUSHED,             /* selected pixelmap id           */
    0                                        /* disabled pixelmap id           */
};
GX_PIXELMAP_BUTTON_PROPERTIES h_menu_window_2_clock_properties =
{
    GX_PIXELMAP_ID_CLOCK_ON,                 /* normal pixelmap id             */
    GX_PIXELMAP_ID_CLOCK_PUSHED,             /* selected pixelmap id           */
    0                                        /* disabled pixelmap id           */
};
GX_PIXELMAP_BUTTON_PROPERTIES h_menu_window_2_contacts_properties =
{
    GX_PIXELMAP_ID_CONTACTS_ON,              /* normal pixelmap id             */
    GX_PIXELMAP_ID_CONTACTS_PUSHED,          /* selected pixelmap id           */
    0                                        /* disabled pixelmap id           */
};
GX_PIXELMAP_BUTTON_PROPERTIES h_menu_window_2_about_properties =
{
    GX_PIXELMAP_ID_ABOUT_ON,                 /* normal pixelmap id             */
    GX_PIXELMAP_ID_ABOUT_PUSHED,             /* selected pixelmap id           */
    0                                        /* disabled pixelmap id           */
};

GX_CONST GX_STUDIO_WIDGET h_menu_window_2_about_define =
{
    "about",
    GX_TYPE_PIXELMAP_BUTTON,                 /* widget type                    */
    ID_ABOUT,                                /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PIXELMAP_BUTTON),              /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_LOWER,                   /* disabled color id              */
    gx_studio_pixelmap_button_create,        /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {212, 0, 266, 52},                       /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */
    offsetof(H_MENU_WINDOW_2_CONTROL_BLOCK, h_menu_window_2_about), /* control block */
    (void *) &h_menu_window_2_about_properties /* extended properties          */
};

GX_CONST GX_STUDIO_WIDGET h_menu_window_2_contacts_define =
{
    "contacts",
    GX_TYPE_PIXELMAP_BUTTON,                 /* widget type                    */
    ID_CONTACTS,                             /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PIXELMAP_BUTTON),              /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_LOWER,                   /* disabled color id              */
    gx_studio_pixelmap_button_create,        /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {145, 0, 199, 52},                       /* widget size                    */
    &h_menu_window_2_about_define,           /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */
    offsetof(H_MENU_WINDOW_2_CONTROL_BLOCK, h_menu_window_2_contacts), /* control block */
    (void *) &h_menu_window_2_contacts_properties /* extended properties       */
};

GX_CONST GX_STUDIO_WIDGET h_menu_window_2_clock_define =
{
    "clock",
    GX_TYPE_PIXELMAP_BUTTON,                 /* widget type                    */
    ID_CLOCK,                                /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PIXELMAP_BUTTON),              /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_LOWER,                   /* disabled color id              */
    gx_studio_pixelmap_button_create,        /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {78, 0, 132, 52},                        /* widget size                    */
    &h_menu_window_2_contacts_define,        /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */
    offsetof(H_MENU_WINDOW_2_CONTROL_BLOCK, h_menu_window_2_clock), /* control block */
    (void *) &h_menu_window_2_clock_properties /* extended properties          */
};

GX_CONST GX_STUDIO_WIDGET h_menu_window_2_games_define =
{
    "games",
    GX_TYPE_PIXELMAP_BUTTON,                 /* widget type                    */
    ID_GAMES,                                /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PIXELMAP_BUTTON),              /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_LOWER,                   /* disabled color id              */
    gx_studio_pixelmap_button_create,        /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {11, 0, 65, 52},                         /* widget size                    */
    &h_menu_window_2_clock_define,           /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */
    offsetof(H_MENU_WINDOW_2_CONTROL_BLOCK, h_menu_window_2_games), /* control block */
    (void *) &h_menu_window_2_games_properties /* extended properties          */
};

GX_CONST GX_STUDIO_WIDGET h_menu_window_2_define =
{
    "h_menu_window_2",
    GX_TYPE_WINDOW,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT,   /* style flags                */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(H_MENU_WINDOW_2_CONTROL_BLOCK),   /* control block size             */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_WINDOW_FILL,                 /* selected color id              */
    GX_COLOR_ID_WINDOW_FILL,                 /* disabled color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {0, 0, 278, 52},                         /* widget size                    */
    GX_NULL,                                 /* next widget                    */
    &h_menu_window_2_games_define,           /* child widget                   */
    0,                                       /* control block                  */
    (void *) &h_menu_window_2_properties     /* extended properties            */
};
GX_WINDOW_PROPERTIES h_menu_window_3_properties =
{
    0                                        /* wallpaper pixelmap id          */
};
GX_PIXELMAP_BUTTON_PROPERTIES h_menu_window_3_map_1_properties =
{
    GX_PIXELMAP_ID_MAP_ON,                   /* normal pixelmap id             */
    GX_PIXELMAP_ID_MAP_PUSHED,               /* selected pixelmap id           */
    0                                        /* disabled pixelmap id           */
};
GX_PIXELMAP_BUTTON_PROPERTIES h_menu_window_3_settings_1_properties =
{
    GX_PIXELMAP_ID_SETTINGS_ON,              /* normal pixelmap id             */
    GX_PIXELMAP_ID_SETTINGS_PUSHED,          /* selected pixelmap id           */
    0                                        /* disabled pixelmap id           */
};
GX_PIXELMAP_BUTTON_PROPERTIES h_menu_window_3_map_properties =
{
    GX_PIXELMAP_ID_MAP_ON,                   /* normal pixelmap id             */
    GX_PIXELMAP_ID_MAP_PUSHED,               /* selected pixelmap id           */
    0                                        /* disabled pixelmap id           */
};
GX_PIXELMAP_BUTTON_PROPERTIES h_menu_window_3_settings_properties =
{
    GX_PIXELMAP_ID_SETTINGS_ON,              /* normal pixelmap id             */
    GX_PIXELMAP_ID_SETTINGS_PUSHED,          /* selected pixelmap id           */
    0                                        /* disabled pixelmap id           */
};

GX_CONST GX_STUDIO_WIDGET h_menu_window_3_settings_define =
{
    "settings",
    GX_TYPE_PIXELMAP_BUTTON,                 /* widget type                    */
    ID_SETTINGS,                             /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PIXELMAP_BUTTON),              /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_LOWER,                   /* disabled color id              */
    gx_studio_pixelmap_button_create,        /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {214, 0, 268, 52},                       /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */
    offsetof(H_MENU_WINDOW_3_CONTROL_BLOCK, h_menu_window_3_settings), /* control block */
    (void *) &h_menu_window_3_settings_properties /* extended properties       */
};

GX_CONST GX_STUDIO_WIDGET h_menu_window_3_map_define =
{
    "map",
    GX_TYPE_PIXELMAP_BUTTON,                 /* widget type                    */
    ID_MAP,                                  /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PIXELMAP_BUTTON),              /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_LOWER,                   /* disabled color id              */
    gx_studio_pixelmap_button_create,        /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {146, 0, 200, 52},                       /* widget size                    */
    &h_menu_window_3_settings_define,        /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */
    offsetof(H_MENU_WINDOW_3_CONTROL_BLOCK, h_menu_window_3_map), /* control block */
    (void *) &h_menu_window_3_map_properties /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET h_menu_window_3_settings_1_define =
{
    "settings_1",
    GX_TYPE_PIXELMAP_BUTTON,                 /* widget type                    */
    ID_SETTINGS,                             /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PIXELMAP_BUTTON),              /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_LOWER,                   /* disabled color id              */
    gx_studio_pixelmap_button_create,        /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {78, 0, 132, 52},                        /* widget size                    */
    &h_menu_window_3_map_define,             /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */
    offsetof(H_MENU_WINDOW_3_CONTROL_BLOCK, h_menu_window_3_settings_1), /* control block */
    (void *) &h_menu_window_3_settings_1_properties /* extended properties     */
};

GX_CONST GX_STUDIO_WIDGET h_menu_window_3_map_1_define =
{
    "map_1",
    GX_TYPE_PIXELMAP_BUTTON,                 /* widget type                    */
    ID_MAP,                                  /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PIXELMAP_BUTTON),              /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_LOWER,                   /* disabled color id              */
    gx_studio_pixelmap_button_create,        /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {11, 0, 65, 52},                         /* widget size                    */
    &h_menu_window_3_settings_1_define,      /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */
    offsetof(H_MENU_WINDOW_3_CONTROL_BLOCK, h_menu_window_3_map_1), /* control block */
    (void *) &h_menu_window_3_map_1_properties /* extended properties          */
};

GX_CONST GX_STUDIO_WIDGET h_menu_window_3_define =
{
    "h_menu_window_3",
    GX_TYPE_WINDOW,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT,   /* style flags                */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(H_MENU_WINDOW_3_CONTROL_BLOCK),   /* control block size             */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_WINDOW_FILL,                 /* selected color id              */
    GX_COLOR_ID_WINDOW_FILL,                 /* disabled color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {0, 0, 278, 52},                         /* widget size                    */
    GX_NULL,                                 /* next widget                    */
    &h_menu_window_3_map_1_define,           /* child widget                   */
    0,                                       /* control block                  */
    (void *) &h_menu_window_3_properties     /* extended properties            */
};
GX_WINDOW_PROPERTIES main_screen_properties =
{
    0                                        /* wallpaper pixelmap id          */
};
GX_WINDOW_PROPERTIES main_screen_h_menu_window_properties =
{
    0                                        /* wallpaper pixelmap id          */
};
GX_WINDOW_PROPERTIES main_screen_h_menu_window_1_properties =
{
    0                                        /* wallpaper pixelmap id          */
};
GX_PIXELMAP_BUTTON_PROPERTIES main_screen_message_properties =
{
    GX_PIXELMAP_ID_MESSAGES_ON,              /* normal pixelmap id             */
    GX_PIXELMAP_ID_MESSAGES_PUSHED,          /* selected pixelmap id           */
    0                                        /* disabled pixelmap id           */
};
GX_PIXELMAP_BUTTON_PROPERTIES main_screen_weather_properties =
{
    GX_PIXELMAP_ID_WEATHER_ON,               /* normal pixelmap id             */
    GX_PIXELMAP_ID_WEATHER_PUSHED,           /* selected pixelmap id           */
    0                                        /* disabled pixelmap id           */
};
GX_PIXELMAP_BUTTON_PROPERTIES main_screen_calculator_properties =
{
    GX_PIXELMAP_ID_CALCULATOR_ON,            /* normal pixelmap id             */
    GX_PIXELMAP_ID_CALCULATOR_PUSHED,        /* selected pixelmap id           */
    0                                        /* disabled pixelmap id           */
};
GX_PIXELMAP_BUTTON_PROPERTIES main_screen_healthy_properties =
{
    GX_PIXELMAP_ID_HEALTH_ON,                /* normal pixelmap id             */
    GX_PIXELMAP_ID_HEALTH_PUSHED,            /* selected pixelmap id           */
    0                                        /* disabled pixelmap id           */
};
GX_WINDOW_PROPERTIES main_screen_v_menu_window_properties =
{
    0                                        /* wallpaper pixelmap id          */
};
GX_WINDOW_PROPERTIES main_screen_v_menu_window_1_properties =
{
    0                                        /* wallpaper pixelmap id          */
};
GX_PIXELMAP_BUTTON_PROPERTIES main_screen_message_1_properties =
{
    GX_PIXELMAP_ID_MESSAGES_ON,              /* normal pixelmap id             */
    GX_PIXELMAP_ID_MESSAGES_PUSHED,          /* selected pixelmap id           */
    0                                        /* disabled pixelmap id           */
};
GX_PIXELMAP_BUTTON_PROPERTIES main_screen_weather_1_properties =
{
    GX_PIXELMAP_ID_WEATHER_ON,               /* normal pixelmap id             */
    GX_PIXELMAP_ID_WEATHER_PUSHED,           /* selected pixelmap id           */
    0                                        /* disabled pixelmap id           */
};
GX_PIXELMAP_BUTTON_PROPERTIES main_screen_calculator_1_properties =
{
    GX_PIXELMAP_ID_CALCULATOR_ON,            /* normal pixelmap id             */
    GX_PIXELMAP_ID_CALCULATOR_PUSHED,        /* selected pixelmap id           */
    0                                        /* disabled pixelmap id           */
};
GX_PIXELMAP_BUTTON_PROPERTIES main_screen_healthy_1_properties =
{
    GX_PIXELMAP_ID_HEALTH_ON,                /* normal pixelmap id             */
    GX_PIXELMAP_ID_HEALTH_PUSHED,            /* selected pixelmap id           */
    0                                        /* disabled pixelmap id           */
};
GX_PROMPT_PROPERTIES main_screen_prompt_properties =
{
    GX_STRING_ID_STRING_2,                   /* string id                      */
    GX_FONT_ID_PROMPT,                       /* font id                        */
    GX_COLOR_ID_SELECTED_FILL,               /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected text color            */
    GX_COLOR_ID_SELECTED_FILL                /* disabled text color            */
};
GX_NUMERIC_PROMPT_PROPERTIES main_screen_v_animation_count_prompt_properties =
{
    0,                                       /* string id                      */
    GX_FONT_ID_PROMPT,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected text color            */
    GX_COLOR_ID_TEXT,                        /* disabled text color            */
    GX_NULL,                                 /* format function                */
    0                                        /* numeric prompt value           */
};
GX_NUMERIC_PROMPT_PROPERTIES main_screen_h_animation_count_prompt_properties =
{
    0,                                       /* string id                      */
    GX_FONT_ID_PROMPT,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected text color            */
    GX_COLOR_ID_TEXT,                        /* disabled text color            */
    GX_NULL,                                 /* format function                */
    0                                        /* numeric prompt value           */
};

GX_CONST GX_STUDIO_WIDGET main_screen_healthy_define =
{
    "healthy",
    GX_TYPE_PIXELMAP_BUTTON,                 /* widget type                    */
    ID_HEALTHY,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PIXELMAP_BUTTON),              /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_LOWER,                   /* disabled color id              */
    gx_studio_pixelmap_button_create,        /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {280, 97, 334, 149},                     /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */
    offsetof(MAIN_SCREEN_CONTROL_BLOCK, main_screen_healthy), /* control block */
    (void *) &main_screen_healthy_properties /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET main_screen_calculator_define =
{
    "calculator",
    GX_TYPE_PIXELMAP_BUTTON,                 /* widget type                    */
    ID_CALCULATOR,                           /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PIXELMAP_BUTTON),              /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_LOWER,                   /* disabled color id              */
    gx_studio_pixelmap_button_create,        /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {213, 97, 267, 149},                     /* widget size                    */
    &main_screen_healthy_define,             /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */
    offsetof(MAIN_SCREEN_CONTROL_BLOCK, main_screen_calculator), /* control block */
    (void *) &main_screen_calculator_properties /* extended properties         */
};

GX_CONST GX_STUDIO_WIDGET main_screen_weather_define =
{
    "weather",
    GX_TYPE_PIXELMAP_BUTTON,                 /* widget type                    */
    ID_WEATHER,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PIXELMAP_BUTTON),              /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_LOWER,                   /* disabled color id              */
    gx_studio_pixelmap_button_create,        /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {146, 97, 200, 149},                     /* widget size                    */
    &main_screen_calculator_define,          /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */
    offsetof(MAIN_SCREEN_CONTROL_BLOCK, main_screen_weather), /* control block */
    (void *) &main_screen_weather_properties /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET main_screen_message_define =
{
    "message",
    GX_TYPE_PIXELMAP_BUTTON,                 /* widget type                    */
    ID_MESSAGE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PIXELMAP_BUTTON),              /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_LOWER,                   /* disabled color id              */
    gx_studio_pixelmap_button_create,        /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {79, 97, 133, 149},                      /* widget size                    */
    &main_screen_weather_define,             /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */
    offsetof(MAIN_SCREEN_CONTROL_BLOCK, main_screen_message), /* control block */
    (void *) &main_screen_message_properties /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET main_screen_h_menu_window_1_define =
{
    "h_menu_window_1",
    GX_TYPE_WINDOW,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT,   /* style flags                */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_WINDOW),                       /* control block size             */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_WINDOW_FILL,                 /* selected color id              */
    GX_COLOR_ID_WINDOW_FILL,                 /* disabled color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {69, 97, 347, 149},                      /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    &main_screen_message_define,             /* child widget definition        */
    offsetof(MAIN_SCREEN_CONTROL_BLOCK, main_screen_h_menu_window_1), /* control block */
    (void *) &main_screen_h_menu_window_1_properties /* extended properties    */
};

GX_CONST GX_STUDIO_WIDGET main_screen_healthy_1_define =
{
    "healthy_1",
    GX_TYPE_PIXELMAP_BUTTON,                 /* widget type                    */
    ID_HEALTHY,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PIXELMAP_BUTTON),              /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_LOWER,                   /* disabled color id              */
    gx_studio_pixelmap_button_create,        /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {268, 410, 322, 462},                    /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */
    offsetof(MAIN_SCREEN_CONTROL_BLOCK, main_screen_healthy_1), /* control block */
    (void *) &main_screen_healthy_1_properties /* extended properties          */
};

GX_CONST GX_STUDIO_WIDGET main_screen_calculator_1_define =
{
    "calculator_1",
    GX_TYPE_PIXELMAP_BUTTON,                 /* widget type                    */
    ID_CALCULATOR,                           /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PIXELMAP_BUTTON),              /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_LOWER,                   /* disabled color id              */
    gx_studio_pixelmap_button_create,        /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {268, 350, 322, 402},                    /* widget size                    */
    &main_screen_healthy_1_define,           /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */
    offsetof(MAIN_SCREEN_CONTROL_BLOCK, main_screen_calculator_1), /* control block */
    (void *) &main_screen_calculator_1_properties /* extended properties       */
};

GX_CONST GX_STUDIO_WIDGET main_screen_weather_1_define =
{
    "weather_1",
    GX_TYPE_PIXELMAP_BUTTON,                 /* widget type                    */
    ID_WEATHER,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PIXELMAP_BUTTON),              /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_LOWER,                   /* disabled color id              */
    gx_studio_pixelmap_button_create,        /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {268, 290, 322, 342},                    /* widget size                    */
    &main_screen_calculator_1_define,        /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */
    offsetof(MAIN_SCREEN_CONTROL_BLOCK, main_screen_weather_1), /* control block */
    (void *) &main_screen_weather_1_properties /* extended properties          */
};

GX_CONST GX_STUDIO_WIDGET main_screen_message_1_define =
{
    "message_1",
    GX_TYPE_PIXELMAP_BUTTON,                 /* widget type                    */
    ID_MESSAGE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PIXELMAP_BUTTON),              /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_LOWER,                   /* disabled color id              */
    gx_studio_pixelmap_button_create,        /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {268, 230, 322, 282},                    /* widget size                    */
    &main_screen_weather_1_define,           /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */
    offsetof(MAIN_SCREEN_CONTROL_BLOCK, main_screen_message_1), /* control block */
    (void *) &main_screen_message_1_properties /* extended properties          */
};

GX_CONST GX_STUDIO_WIDGET main_screen_v_menu_window_1_define =
{
    "v_menu_window_1",
    GX_TYPE_WINDOW,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT,   /* style flags                */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_WINDOW),                       /* control block size             */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_WINDOW_FILL,                 /* selected color id              */
    GX_COLOR_ID_WINDOW_FILL,                 /* disabled color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {258, 221, 335, 468},                    /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    &main_screen_message_1_define,           /* child widget definition        */
    offsetof(MAIN_SCREEN_CONTROL_BLOCK, main_screen_v_menu_window_1), /* control block */
    (void *) &main_screen_v_menu_window_1_properties /* extended properties    */
};

GX_CONST GX_STUDIO_WIDGET main_screen_h_animation_count_prompt_define =
{
    "h_animation_count_prompt",
    GX_TYPE_NUMERIC_PROMPT,                  /* widget type                    */
    ID_H_ANIMATION_COUNT,                    /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_THIN|GX_STYLE_TRANSPARENT|GX_STYLE_TEXT_CENTER,   /* style flags */
    0,                                       /* status flags                   */
    sizeof(GX_NUMERIC_PROMPT),               /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_WIDGET_FILL,                 /* disabled color id              */
    gx_studio_numeric_prompt_create,         /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {359, 146, 438, 169},                    /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */
    offsetof(MAIN_SCREEN_CONTROL_BLOCK, main_screen_h_animation_count_prompt), /* control block */
    (void *) &main_screen_h_animation_count_prompt_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET main_screen_v_animation_count_prompt_define =
{
    "v_animation_count_prompt",
    GX_TYPE_NUMERIC_PROMPT,                  /* widget type                    */
    ID_V_ANIMATION_COUNT,                    /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_THIN|GX_STYLE_TRANSPARENT|GX_STYLE_TEXT_CENTER,   /* style flags */
    0,                                       /* status flags                   */
    sizeof(GX_NUMERIC_PROMPT),               /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_WIDGET_FILL,                 /* disabled color id              */
    gx_studio_numeric_prompt_create,         /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {359, 439, 438, 462},                    /* widget size                    */
    &main_screen_h_animation_count_prompt_define, /* next widget definition    */
    GX_NULL,                                 /* no child widgets               */
    offsetof(MAIN_SCREEN_CONTROL_BLOCK, main_screen_v_animation_count_prompt), /* control block */
    (void *) &main_screen_v_animation_count_prompt_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET main_screen_prompt_define =
{
    "prompt",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_TEXT_CENTER,   /* style flags */
    0,                                       /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_SELECTED_FILL,               /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_SELECTED_FILL,               /* disabled color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {211, 21, 379, 38},                      /* widget size                    */
    &main_screen_v_animation_count_prompt_define, /* next widget definition    */
    GX_NULL,                                 /* no child widgets               */
    offsetof(MAIN_SCREEN_CONTROL_BLOCK, main_screen_prompt), /* control block  */
    (void *) &main_screen_prompt_properties  /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET main_screen_v_menu_window_define =
{
    "v_menu_window",
    GX_TYPE_WINDOW,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_THIN|GX_STYLE_TRANSPARENT|GX_STYLE_DRAW_SELECTED|GX_STYLE_ENABLED,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_WINDOW),                       /* control block size             */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_WINDOW_FILL,                 /* selected color id              */
    GX_COLOR_ID_WINDOW_FILL,                 /* disabled color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    (UINT (*)(GX_WIDGET *, GX_EVENT *)) v_menu_window_event_handler, /* event function override */
    {242, 221, 347, 468},                    /* widget size                    */
    &main_screen_prompt_define,              /* next widget definition         */
    &main_screen_v_menu_window_1_define,     /* child widget definition        */
    offsetof(MAIN_SCREEN_CONTROL_BLOCK, main_screen_v_menu_window), /* control block */
    (void *) &main_screen_v_menu_window_properties /* extended properties      */
};

GX_CONST GX_STUDIO_WIDGET main_screen_h_menu_window_define =
{
    "h_menu_window",
    GX_TYPE_WINDOW,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_THIN|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_WINDOW),                       /* control block size             */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_WINDOW_FILL,                 /* selected color id              */
    GX_COLOR_ID_WINDOW_FILL,                 /* disabled color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    (UINT (*)(GX_WIDGET *, GX_EVENT *)) h_menu_window_event_handler, /* event function override */
    {69, 81, 347, 168},                      /* widget size                    */
    &main_screen_v_menu_window_define,       /* next widget definition         */
    &main_screen_h_menu_window_1_define,     /* child widget definition        */
    offsetof(MAIN_SCREEN_CONTROL_BLOCK, main_screen_h_menu_window), /* control block */
    (void *) &main_screen_h_menu_window_properties /* extended properties      */
};

GX_CONST GX_STUDIO_WIDGET main_screen_define =
{
    "main_screen",
    GX_TYPE_WINDOW,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_THIN|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(MAIN_SCREEN_CONTROL_BLOCK),       /* control block size             */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_WINDOW_FILL,                 /* selected color id              */
    GX_COLOR_ID_WINDOW_FILL,                 /* disabled color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {0, 0, 639, 479},                        /* widget size                    */
    GX_NULL,                                 /* next widget                    */
    &main_screen_h_menu_window_define,       /* child widget                   */
    0,                                       /* control block                  */
    (void *) &main_screen_properties         /* extended properties            */
};
GX_CONST GX_STUDIO_WIDGET_ENTRY screen_drag_animation_with_block_move_widget_table[] =
{
    { &v_menu_window_3_define, (GX_WIDGET *) &v_menu_window_3 },
    { &v_menu_window_2_define, (GX_WIDGET *) &v_menu_window_2 },
    { &h_menu_window_2_define, (GX_WIDGET *) &h_menu_window_2 },
    { &h_menu_window_3_define, (GX_WIDGET *) &h_menu_window_3 },
    { &main_screen_define, (GX_WIDGET *) &main_screen },
    {GX_NULL, GX_NULL}
};

UINT gx_studio_named_widget_create(char *name, GX_WIDGET *parent, GX_WIDGET **new_widget)
{
    return gx_studio_named_widget_create_from_table(name, parent, new_widget, screen_drag_animation_with_block_move_widget_table);
}

UINT gx_studio_display_configure(USHORT display, UINT (*driver)(GX_DISPLAY *),
    GX_UBYTE language, USHORT theme, GX_WINDOW_ROOT **return_root)
{
    GX_STUDIO_DISPLAY_INFO *display_info = &screen_drag_animation_with_block_move_display_table[display];
    return gx_studio_display_config(display_info, driver, language, theme, return_root);
}
#undef GUIX_STUDIO_GENERATED_FILE
