/***************************************************************************
 * Copyright (c) 2024 Microsoft Corporation
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * SPDX-License-Identifier: MIT
 **************************************************************************/

/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  specification file(s). For more information please refer to the Azure RTOS */
/*  GUIX Studio User Guide, or visit our web site at azure.com/rtos            */
/*                                                                             */
/*  GUIX Studio Revision 6.2.0.1                                               */
/*  Date (dd.mm.yyyy): 31.10.2022   Time (hh:mm): 14:10                        */
/*******************************************************************************/


#ifndef _LINE_CHART_SPECIFICATIONS_H_
#define _LINE_CHART_SPECIFICATIONS_H_

#include "gx_studio_widget.h"

/* Define widget ids                                                           */



/* Define animation ids                                                        */

#define GX_NEXT_ANIMATION_ID 1


/* Define user event ids                                                       */

#define GX_NEXT_USER_EVENT_ID GX_FIRST_USER_EVENT


/* Declare top-level control blocks                                            */

struct PRESSURE_TREND_FRAME_CONTROL_BLOCK : public GX_WINDOW
{
    GX_WINDOW pressure_trend_frame_title_bar;
    GX_PROMPT pressure_trend_frame_prompt;
    GX_PROMPT pressure_trend_frame_prompt_1;
    GX_PIXELMAP_PROMPT pressure_trend_frame_prompt_2;
    GX_PIXELMAP_PROMPT pressure_trend_frame_prompt_3;
    GX_PIXELMAP_PROMPT pressure_trend_frame_prompt_4;
    GX_LINE_CHART pressure_trend_frame_line_chart;
};


/* extern statically defined control blocks                                    */

#ifndef GUIX_STUDIO_GENERATED_FILE
extern PRESSURE_TREND_FRAME_CONTROL_BLOCK pressure_trend_frame;
#endif

/* Declare event process functions, draw functions, and callback functions     */

UINT trend_frame_event_process(GX_WINDOW *widget, GX_EVENT *event_ptr);
VOID test_line_chart_draw(GX_LINE_CHART *widget);


/* Declare Studio-generated functions for creating top-level widgets           */

UINT gx_studio_named_widget_create(char *name, GX_WIDGET *parent, GX_WIDGET **new_widget);
UINT gx_studio_display_configure(USHORT display, UINT (*driver)(GX_DISPLAY *), GX_UBYTE language, USHORT theme, GX_WINDOW_ROOT **return_root);

#endif                                       /* sentry                         */
