/***************************************************************************
 * Copyright (c) 2024 Microsoft Corporation
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * SPDX-License-Identifier: MIT
 **************************************************************************/

/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  specification file(s). For more information please refer to the Azure RTOS */
/*  GUIX Studio User Guide, or visit our web site at azure.com/rtos            */
/*                                                                             */
/*  GUIX Studio Revision 6.2.0.1                                               */
/*  Date (dd.mm.yyyy): 31.10.2022   Time (hh:mm): 14:11                        */
/*******************************************************************************/


#define GUIX_STUDIO_GENERATED_FILE
#include <stddef.h>
#include "radial_progress_bar_resources.h"
#include "radial_progress_bar_specifications.h"

PROGRESS_BAR_WINDOW_CONTROL_BLOCK progress_bar_window;
GX_DISPLAY display_1_control_block;
GX_WINDOW_ROOT display_1_root_window;
GX_CANVAS  display_1_canvas_control_block;
ULONG      display_1_canvas_memory[307200];

extern GX_CONST GX_THEME *display_1_theme_table[];
extern GX_CONST GX_STRING *display_1_language_table[];

GX_STUDIO_DISPLAY_INFO radial_progress_bar_display_table[1] =
{
    {
    "display_1",
    "display_1_canvas",
    display_1_theme_table,
    display_1_language_table,
    DISPLAY_1_THEME_TABLE_SIZE,
    DISPLAY_1_LANGUAGE_TABLE_SIZE,
    DISPLAY_1_STRING_TABLE_SIZE,
    640,                                     /* x resolution                   */
    480,                                     /* y resolution                   */
    &display_1_control_block,
    &display_1_canvas_control_block,
    &display_1_root_window,
    display_1_canvas_memory,                 /* canvas memory area             */
    1228800,                                 /* canvas memory size in bytes    */
    0                                        /* rotation angle                 */
    }
};


GX_WINDOW_PROPERTIES progress_bar_window_properties =
{
    GX_PIXELMAP_ID_BG_TILE                   /* wallpaper pixelmap id          */
};
GX_PIXELMAP_SLIDER_PROPERTIES progress_bar_window_pixelmap_slider_properties =
{
    -360,                                    /* minimum value                  */
    360,                                     /* maximum value                  */
    100,                                     /* current value                  */
    10,                                      /* increment                      */
    10,                                      /* minimum travel                 */
    10,                                      /* maximum travel                 */
    5,                                       /* needle width                   */
    10,                                      /* needle height                  */
    2,                                       /* needle inset                   */
    10,                                      /* needle hotspot                 */
    GX_PIXELMAP_ID_I_ORANGEFILL_MIDDLE_HORIZONTAL, /* lower pixelmap id        */
    GX_PIXELMAP_ID_I_EMPTYFILL_MIDDLE_HORIZONTAL, /* upper pixelmap id         */
    GX_PIXELMAP_ID_I_INDICATOR_HORIZONTAL    /* needle pixelmap id             */
};
GX_ICON_PROPERTIES progress_bar_window_icon_3_properties =
{
    GX_PIXELMAP_ID_I_ORANGEFILL_LEFT,        /* normal pixelmap id             */
    0                                        /* selected pixelmap id           */
};
GX_ICON_PROPERTIES progress_bar_window_icon_4_properties =
{
    GX_PIXELMAP_ID_I_EMPTYFILL_RIGHT,        /* normal pixelmap id             */
    0                                        /* selected pixelmap id           */
};
GX_CHECKBOX_PROPERTIES progress_bar_window_checkbox_properties =
{
    GX_STRING_ID_STRING_8,                   /* string id                      */
    GX_FONT_ID_BUTTON,                       /* font id                        */
    GX_COLOR_ID_RED,                         /* normal text color              */
    GX_COLOR_ID_RED,                         /* selected text color            */
    GX_COLOR_ID_RED,                         /* disabled text color            */
    0,                                       /* unchecked pixelmap id          */
    0,                                       /* checked pixelmap id            */
    0,                                       /* unchecked disabled pixelmap id */
    0                                        /* checked disabled pixelmap id   */
};
GX_CHECKBOX_PROPERTIES progress_bar_window_checkbox_1_properties =
{
    GX_STRING_ID_STRING_9,                   /* string id                      */
    GX_FONT_ID_BUTTON,                       /* font id                        */
    GX_COLOR_ID_RED,                         /* normal text color              */
    GX_COLOR_ID_RED,                         /* selected text color            */
    GX_COLOR_ID_RED,                         /* disabled text color            */
    0,                                       /* unchecked pixelmap id          */
    0,                                       /* checked pixelmap id            */
    0,                                       /* unchecked disabled pixelmap id */
    0                                        /* checked disabled pixelmap id   */
};
GX_CHECKBOX_PROPERTIES progress_bar_window_checkbox_2_properties =
{
    GX_STRING_ID_STRING_12,                  /* string id                      */
    GX_FONT_ID_BUTTON,                       /* font id                        */
    GX_COLOR_ID_RED,                         /* normal text color              */
    GX_COLOR_ID_RED,                         /* selected text color            */
    GX_COLOR_ID_RED,                         /* disabled text color            */
    0,                                       /* unchecked pixelmap id          */
    0,                                       /* checked pixelmap id            */
    0,                                       /* unchecked disabled pixelmap id */
    0                                        /* checked disabled pixelmap id   */
};
GX_SLIDER_PROPERTIES progress_bar_window_slider_properties =
{
    10,                                      /* tickmark count                 */
    2,                                       /* mimimun value                  */
    30,                                      /* maximum value                  */
    20,                                      /* current value                  */
    10,                                      /* increment                      */
    10,                                      /* minimum travel                 */
    10,                                      /* maximum travel                 */
    5,                                       /* needle width                   */
    15,                                      /* needle height                  */
    5,                                       /* needle inset                   */
    2                                        /* needle hotspot                 */
};
GX_SLIDER_PROPERTIES progress_bar_window_slider_1_properties =
{
    10,                                      /* tickmark count                 */
    10,                                      /* mimimun value                  */
    120,                                     /* maximum value                  */
    100,                                     /* current value                  */
    10,                                      /* increment                      */
    10,                                      /* minimum travel                 */
    10,                                      /* maximum travel                 */
    5,                                       /* needle width                   */
    15,                                      /* needle height                  */
    5,                                       /* needle inset                   */
    2                                        /* needle hotspot                 */
};
GX_SLIDER_PROPERTIES progress_bar_window_slider_2_properties =
{
    10,                                      /* tickmark count                 */
    2,                                       /* mimimun value                  */
    30,                                      /* maximum value                  */
    20,                                      /* current value                  */
    10,                                      /* increment                      */
    10,                                      /* minimum travel                 */
    10,                                      /* maximum travel                 */
    5,                                       /* needle width                   */
    15,                                      /* needle height                  */
    5,                                       /* needle inset                   */
    2                                        /* needle hotspot                 */
};
GX_PROMPT_PROPERTIES progress_bar_window_prompt_properties =
{
    GX_STRING_ID_STRING_19,                  /* string id                      */
    GX_FONT_ID_PROMPT,                       /* font id                        */
    GX_COLOR_ID_TEXT_INPUT_TEXT,             /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected text color            */
    GX_COLOR_ID_TEXT_INPUT_TEXT              /* disabled text color            */
};
GX_PROMPT_PROPERTIES progress_bar_window_prompt_1_properties =
{
    GX_STRING_ID_STRING_18,                  /* string id                      */
    GX_FONT_ID_PROMPT,                       /* font id                        */
    GX_COLOR_ID_TEXT_INPUT_TEXT,             /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected text color            */
    GX_COLOR_ID_TEXT_INPUT_TEXT              /* disabled text color            */
};
GX_PROMPT_PROPERTIES progress_bar_window_prompt_2_properties =
{
    GX_STRING_ID_STRING_17,                  /* string id                      */
    GX_FONT_ID_PROMPT,                       /* font id                        */
    GX_COLOR_ID_TEXT_INPUT_TEXT,             /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected text color            */
    GX_COLOR_ID_TEXT_INPUT_TEXT              /* disabled text color            */
};
GX_PROMPT_PROPERTIES progress_bar_window_normal_width_prompt_properties =
{
    GX_STRING_ID_STRING_20,                  /* string id                      */
    GX_FONT_ID_PROMPT,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected text color            */
    GX_COLOR_ID_TEXT                         /* disabled text color            */
};
GX_PROMPT_PROPERTIES progress_bar_window_selected_width_prompt_properties =
{
    GX_STRING_ID_STRING_20,                  /* string id                      */
    GX_FONT_ID_PROMPT,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected text color            */
    GX_COLOR_ID_TEXT                         /* disabled text color            */
};
GX_PROMPT_PROPERTIES progress_bar_window_radius_prompt_properties =
{
    GX_STRING_ID_STRING_21,                  /* string id                      */
    GX_FONT_ID_PROMPT,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected text color            */
    GX_COLOR_ID_TEXT                         /* disabled text color            */
};
GX_PROMPT_PROPERTIES progress_bar_window_prompt_3_properties =
{
    GX_STRING_ID_STRING_22,                  /* string id                      */
    GX_FONT_ID_NEWFONT,                      /* font id                        */
    GX_COLOR_ID_GREEN,                       /* normal text color              */
    GX_COLOR_ID_GREEN,                       /* selected text color            */
    GX_COLOR_ID_GREEN                        /* disabled text color            */
};
GX_PROMPT_PROPERTIES progress_bar_window_prompt_4_properties =
{
    GX_STRING_ID_STRING_23,                  /* string id                      */
    GX_FONT_ID_PROMPT,                       /* font id                        */
    GX_COLOR_ID_TEXT_INPUT_TEXT,             /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected text color            */
    GX_COLOR_ID_TEXT_INPUT_TEXT              /* disabled text color            */
};
GX_SLIDER_PROPERTIES progress_bar_window_slider_3_properties =
{
    10,                                      /* tickmark count                 */
    0,                                       /* mimimun value                  */
    360,                                     /* maximum value                  */
    90,                                      /* current value                  */
    10,                                      /* increment                      */
    10,                                      /* minimum travel                 */
    10,                                      /* maximum travel                 */
    5,                                       /* needle width                   */
    15,                                      /* needle height                  */
    5,                                       /* needle inset                   */
    2                                        /* needle hotspot                 */
};
GX_PROMPT_PROPERTIES progress_bar_window_anchor_prompt_properties =
{
    GX_STRING_ID_STRING_24,                  /* string id                      */
    GX_FONT_ID_PROMPT,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected text color            */
    GX_COLOR_ID_TEXT                         /* disabled text color            */
};
GX_RADIAL_PROGRESS_BAR_INFO progress_bar_window_radial_progress_bar_properties =
{
    173,                                     /* xcenter                        */
    229,                                     /* ycenter                        */
    100,                                     /* radius                         */
    -180,                                    /* current val                    */
    90,                                      /* anchor val                     */
    GX_FONT_ID_NEWFONT,                      /* font_id                        */
    GX_COLOR_ID_TEXT_INPUT_TEXT,             /* normal text color              */
    GX_COLOR_ID_TEXT_INPUT_TEXT,             /* selected text color            */
    GX_COLOR_ID_TEXT_INPUT_TEXT,             /* disabled text color            */
    20,                                      /* normal brush width             */
    20,                                      /* selected brush width           */
    GX_COLOR_ID_SLIDER_NEEDLE_FILL,          /* normal brush color             */
    GX_COLOR_ID_SELECTED_FILL,               /* selected brush color           */
};
GX_CHECKBOX_PROPERTIES progress_bar_window_checkbox_3_properties =
{
    GX_STRING_ID_STRING_10,                  /* string id                      */
    GX_FONT_ID_BUTTON,                       /* font id                        */
    GX_COLOR_ID_RED,                         /* normal text color              */
    GX_COLOR_ID_RED,                         /* selected text color            */
    GX_COLOR_ID_RED,                         /* disabled text color            */
    0,                                       /* unchecked pixelmap id          */
    0,                                       /* checked pixelmap id            */
    0,                                       /* unchecked disabled pixelmap id */
    0                                        /* checked disabled pixelmap id   */
};
GX_CHECKBOX_PROPERTIES progress_bar_window_checkbox_4_properties =
{
    GX_STRING_ID_STRING_11,                  /* string id                      */
    GX_FONT_ID_BUTTON,                       /* font id                        */
    GX_COLOR_ID_RED,                         /* normal text color              */
    GX_COLOR_ID_RED,                         /* selected text color            */
    GX_COLOR_ID_RED,                         /* disabled text color            */
    0,                                       /* unchecked pixelmap id          */
    0,                                       /* checked pixelmap id            */
    0,                                       /* unchecked disabled pixelmap id */
    0                                        /* checked disabled pixelmap id   */
};
GX_PROMPT_PROPERTIES progress_bar_window_alpha_properties =
{
    GX_STRING_ID_STRING_25,                  /* string id                      */
    GX_FONT_ID_PROMPT,                       /* font id                        */
    GX_COLOR_ID_TEXT_INPUT_TEXT,             /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected text color            */
    GX_COLOR_ID_TEXT_INPUT_TEXT              /* disabled text color            */
};
GX_SLIDER_PROPERTIES progress_bar_window_alpha_slider_properties =
{
    10,                                      /* tickmark count                 */
    0,                                       /* mimimun value                  */
    255,                                     /* maximum value                  */
    255,                                     /* current value                  */
    10,                                      /* increment                      */
    10,                                      /* minimum travel                 */
    10,                                      /* maximum travel                 */
    5,                                       /* needle width                   */
    15,                                      /* needle height                  */
    5,                                       /* needle inset                   */
    2                                        /* needle hotspot                 */
};
GX_NUMERIC_PROMPT_PROPERTIES progress_bar_window_alpha_prompt_properties =
{
    0,                                       /* string id                      */
    GX_FONT_ID_PROMPT,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected text color            */
    GX_COLOR_ID_TEXT,                        /* disabled text color            */
    GX_NULL,                                 /* format function                */
    255                                      /* numeric prompt value           */
};

GX_CONST GX_STUDIO_WIDGET progress_bar_window_alpha_prompt_define =
{
    "alpha_prompt",
    GX_TYPE_NUMERIC_PROMPT,                  /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_THIN|GX_STYLE_TEXT_CENTER,   /* style flags                */
    0,                                       /* status flags                   */
    sizeof(GX_NUMERIC_PROMPT),               /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_WIDGET_FILL,                 /* disabled color id              */
    gx_studio_numeric_prompt_create,         /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {600, 415, 635, 438},                    /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PROGRESS_BAR_WINDOW_CONTROL_BLOCK, progress_bar_window_alpha_prompt), /* control block */
    (void *) &progress_bar_window_alpha_prompt_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET progress_bar_window_alpha_slider_define =
{
    "alpha_slider",
    GX_TYPE_SLIDER,                          /* widget type                    */
    ID_ALPHA_SLIDER,                         /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED|GX_STYLE_SHOW_NEEDLE|GX_STYLE_SHOW_TICKMARKS,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_SLIDER),                       /* control block size             */
    GX_COLOR_ID_BTN_UPPER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_UPPER,                   /* disabled color id              */
    gx_studio_slider_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {471, 414, 592, 437},                    /* widget size                    */
    &progress_bar_window_alpha_prompt_define, /* next widget definition        */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PROGRESS_BAR_WINDOW_CONTROL_BLOCK, progress_bar_window_alpha_slider), /* control block */
    (void *) &progress_bar_window_alpha_slider_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET progress_bar_window_alpha_define =
{
    "alpha",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_TEXT_CENTER,   /* style flags */
    0,                                       /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_WIDGET_FILL,                 /* disabled color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {337, 415, 393, 438},                    /* widget size                    */
    &progress_bar_window_alpha_slider_define, /* next widget definition        */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PROGRESS_BAR_WINDOW_CONTROL_BLOCK, progress_bar_window_alpha), /* control block */
    (void *) &progress_bar_window_alpha_properties /* extended properties      */
};

GX_CONST GX_STUDIO_WIDGET progress_bar_window_checkbox_4_define =
{
    "checkbox_4",
    GX_TYPE_CHECKBOX,                        /* widget type                    */
    ID_ROUND_END,                            /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_BUTTON_PUSHED|GX_STYLE_BUTTON_TOGGLE|GX_STYLE_TEXT_LEFT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_CHECKBOX),                     /* control block size             */
    GX_COLOR_ID_RED,                         /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_RED,                         /* disabled color id              */
    gx_studio_checkbox_create,               /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {340, 228, 478, 251},                    /* widget size                    */
    &progress_bar_window_alpha_define,       /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PROGRESS_BAR_WINDOW_CONTROL_BLOCK, progress_bar_window_checkbox_4), /* control block */
    (void *) &progress_bar_window_checkbox_4_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET progress_bar_window_checkbox_3_define =
{
    "checkbox_3",
    GX_TYPE_CHECKBOX,                        /* widget type                    */
    ID_ALIAS,                                /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_BUTTON_PUSHED|GX_STYLE_BUTTON_TOGGLE|GX_STYLE_TEXT_LEFT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_CHECKBOX),                     /* control block size             */
    GX_COLOR_ID_RED,                         /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_RED,                         /* disabled color id              */
    gx_studio_checkbox_create,               /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {340, 194, 478, 217},                    /* widget size                    */
    &progress_bar_window_checkbox_4_define,  /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PROGRESS_BAR_WINDOW_CONTROL_BLOCK, progress_bar_window_checkbox_3), /* control block */
    (void *) &progress_bar_window_checkbox_3_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET progress_bar_window_radial_progress_bar_define =
{
    "radial_progress_bar",
    GX_TYPE_RADIAL_PROGRESS_BAR,             /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_PROGRESS_PERCENT|GX_STYLE_PROGRESS_TEXT_DRAW|GX_STYLE_RADIAL_PROGRESS_ALIAS|GX_STYLE_RADIAL_PROGRESS_ROUND,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_RADIAL_PROGRESS_BAR),          /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_WIDGET_FILL,                 /* disabled color id              */
    gx_studio_radial_progress_bar_create,     /* create function               */
    (VOID (*)(GX_WIDGET *)) radial_progress_bar_draw, /* drawing function override */
    GX_NULL,                                 /* event function override        */
    {63, 119, 283, 339},                     /* widget size                    */
    &progress_bar_window_checkbox_3_define,  /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PROGRESS_BAR_WINDOW_CONTROL_BLOCK, progress_bar_window_radial_progress_bar), /* control block */
    (void *) &progress_bar_window_radial_progress_bar_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET progress_bar_window_anchor_prompt_define =
{
    "anchor_prompt",
    GX_TYPE_PROMPT,                          /* widget type                    */
    ID_ANCHOR_PROMPT,                        /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_THIN|GX_STYLE_TEXT_CENTER,   /* style flags                */
    0,                                       /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_WIDGET_FILL,                 /* disabled color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {600, 259, 635, 282},                    /* widget size                    */
    &progress_bar_window_radial_progress_bar_define, /* next widget definition */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PROGRESS_BAR_WINDOW_CONTROL_BLOCK, progress_bar_window_anchor_prompt), /* control block */
    (void *) &progress_bar_window_anchor_prompt_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET progress_bar_window_slider_3_define =
{
    "slider_3",
    GX_TYPE_SLIDER,                          /* widget type                    */
    ID_ANCHOR_SLIDER,                        /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED|GX_STYLE_SHOW_NEEDLE|GX_STYLE_SHOW_TICKMARKS,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_SLIDER),                       /* control block size             */
    GX_COLOR_ID_BTN_UPPER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_UPPER,                   /* disabled color id              */
    gx_studio_slider_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {471, 260, 592, 283},                    /* widget size                    */
    &progress_bar_window_anchor_prompt_define, /* next widget definition       */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PROGRESS_BAR_WINDOW_CONTROL_BLOCK, progress_bar_window_slider_3), /* control block */
    (void *) &progress_bar_window_slider_3_properties /* extended properties   */
};

GX_CONST GX_STUDIO_WIDGET progress_bar_window_prompt_4_define =
{
    "prompt_4",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_TEXT_CENTER,   /* style flags */
    0,                                       /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_WIDGET_FILL,                 /* disabled color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {335, 262, 446, 285},                    /* widget size                    */
    &progress_bar_window_slider_3_define,    /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PROGRESS_BAR_WINDOW_CONTROL_BLOCK, progress_bar_window_prompt_4), /* control block */
    (void *) &progress_bar_window_prompt_4_properties /* extended properties   */
};

GX_CONST GX_STUDIO_WIDGET progress_bar_window_prompt_3_define =
{
    "prompt_3",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_TEXT_CENTER,   /* style flags */
    0,                                       /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_WIDGET_FILL,                 /* disabled color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {161, 30, 491, 60},                      /* widget size                    */
    &progress_bar_window_prompt_4_define,    /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PROGRESS_BAR_WINDOW_CONTROL_BLOCK, progress_bar_window_prompt_3), /* control block */
    (void *) &progress_bar_window_prompt_3_properties /* extended properties   */
};

GX_CONST GX_STUDIO_WIDGET progress_bar_window_radius_prompt_define =
{
    "radius_prompt",
    GX_TYPE_PROMPT,                          /* widget type                    */
    ID_RADIUS_PROMPT,                        /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_THIN|GX_STYLE_TEXT_CENTER,   /* style flags                */
    0,                                       /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_WIDGET_FILL,                 /* disabled color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {600, 381, 635, 404},                    /* widget size                    */
    &progress_bar_window_prompt_3_define,    /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PROGRESS_BAR_WINDOW_CONTROL_BLOCK, progress_bar_window_radius_prompt), /* control block */
    (void *) &progress_bar_window_radius_prompt_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET progress_bar_window_selected_width_prompt_define =
{
    "selected_width_prompt",
    GX_TYPE_PROMPT,                          /* widget type                    */
    ID_SELECTED_WIDTH_PROMPT,                /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_THIN|GX_STYLE_TEXT_CENTER,   /* style flags                */
    0,                                       /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_WIDGET_FILL,                 /* disabled color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {600, 340, 635, 363},                    /* widget size                    */
    &progress_bar_window_radius_prompt_define, /* next widget definition       */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PROGRESS_BAR_WINDOW_CONTROL_BLOCK, progress_bar_window_selected_width_prompt), /* control block */
    (void *) &progress_bar_window_selected_width_prompt_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET progress_bar_window_normal_width_prompt_define =
{
    "normal_width_prompt",
    GX_TYPE_PROMPT,                          /* widget type                    */
    ID_NORMAL_WIDTH_PROMPT,                  /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_THIN|GX_STYLE_TEXT_CENTER,   /* style flags                */
    0,                                       /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_WIDGET_FILL,                 /* disabled color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {600, 301, 635, 324},                    /* widget size                    */
    &progress_bar_window_selected_width_prompt_define, /* next widget definition */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PROGRESS_BAR_WINDOW_CONTROL_BLOCK, progress_bar_window_normal_width_prompt), /* control block */
    (void *) &progress_bar_window_normal_width_prompt_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET progress_bar_window_prompt_2_define =
{
    "prompt_2",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_TEXT_CENTER,   /* style flags */
    0,                                       /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_WIDGET_FILL,                 /* disabled color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {337, 381, 393, 404},                    /* widget size                    */
    &progress_bar_window_normal_width_prompt_define, /* next widget definition */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PROGRESS_BAR_WINDOW_CONTROL_BLOCK, progress_bar_window_prompt_2), /* control block */
    (void *) &progress_bar_window_prompt_2_properties /* extended properties   */
};

GX_CONST GX_STUDIO_WIDGET progress_bar_window_prompt_1_define =
{
    "prompt_1",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_TEXT_CENTER,   /* style flags */
    0,                                       /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_WIDGET_FILL,                 /* disabled color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {337, 342, 457, 365},                    /* widget size                    */
    &progress_bar_window_prompt_2_define,    /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PROGRESS_BAR_WINDOW_CONTROL_BLOCK, progress_bar_window_prompt_1), /* control block */
    (void *) &progress_bar_window_prompt_1_properties /* extended properties   */
};

GX_CONST GX_STUDIO_WIDGET progress_bar_window_prompt_define =
{
    "prompt",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_TEXT_CENTER,   /* style flags */
    0,                                       /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_WIDGET_FILL,                 /* disabled color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {337, 300, 448, 323},                    /* widget size                    */
    &progress_bar_window_prompt_1_define,    /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PROGRESS_BAR_WINDOW_CONTROL_BLOCK, progress_bar_window_prompt), /* control block */
    (void *) &progress_bar_window_prompt_properties /* extended properties     */
};

GX_CONST GX_STUDIO_WIDGET progress_bar_window_slider_2_define =
{
    "slider_2",
    GX_TYPE_SLIDER,                          /* widget type                    */
    ID_SELECTED_WIDTH_SLIDER,                /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED|GX_STYLE_SHOW_NEEDLE|GX_STYLE_SHOW_TICKMARKS,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_SLIDER),                       /* control block size             */
    GX_COLOR_ID_BTN_UPPER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_UPPER,                   /* disabled color id              */
    gx_studio_slider_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {472, 340, 593, 363},                    /* widget size                    */
    &progress_bar_window_prompt_define,      /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PROGRESS_BAR_WINDOW_CONTROL_BLOCK, progress_bar_window_slider_2), /* control block */
    (void *) &progress_bar_window_slider_2_properties /* extended properties   */
};

GX_CONST GX_STUDIO_WIDGET progress_bar_window_slider_1_define =
{
    "slider_1",
    GX_TYPE_SLIDER,                          /* widget type                    */
    ID_RADIUS_SLIDER,                        /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED|GX_STYLE_SHOW_NEEDLE|GX_STYLE_SHOW_TICKMARKS,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_SLIDER),                       /* control block size             */
    GX_COLOR_ID_BTN_UPPER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_UPPER,                   /* disabled color id              */
    gx_studio_slider_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {472, 380, 593, 403},                    /* widget size                    */
    &progress_bar_window_slider_2_define,    /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PROGRESS_BAR_WINDOW_CONTROL_BLOCK, progress_bar_window_slider_1), /* control block */
    (void *) &progress_bar_window_slider_1_properties /* extended properties   */
};

GX_CONST GX_STUDIO_WIDGET progress_bar_window_slider_define =
{
    "slider",
    GX_TYPE_SLIDER,                          /* widget type                    */
    ID_NORMAL_WIDTH_SLIDER,                  /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED|GX_STYLE_SHOW_NEEDLE|GX_STYLE_SHOW_TICKMARKS,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_SLIDER),                       /* control block size             */
    GX_COLOR_ID_BTN_UPPER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_UPPER,                   /* disabled color id              */
    gx_studio_slider_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {472, 300, 593, 323},                    /* widget size                    */
    &progress_bar_window_slider_1_define,    /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PROGRESS_BAR_WINDOW_CONTROL_BLOCK, progress_bar_window_slider), /* control block */
    (void *) &progress_bar_window_slider_properties /* extended properties     */
};

GX_CONST GX_STUDIO_WIDGET progress_bar_window_checkbox_2_define =
{
    "checkbox_2",
    GX_TYPE_CHECKBOX,                        /* widget type                    */
    ID_TRANSPARENT,                          /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_BUTTON_PUSHED|GX_STYLE_BUTTON_TOGGLE|GX_STYLE_TEXT_LEFT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_CHECKBOX),                     /* control block size             */
    GX_COLOR_ID_RED,                         /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_RED,                         /* disabled color id              */
    gx_studio_checkbox_create,               /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {340, 160, 478, 183},                    /* widget size                    */
    &progress_bar_window_slider_define,      /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PROGRESS_BAR_WINDOW_CONTROL_BLOCK, progress_bar_window_checkbox_2), /* control block */
    (void *) &progress_bar_window_checkbox_2_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET progress_bar_window_checkbox_1_define =
{
    "checkbox_1",
    GX_TYPE_CHECKBOX,                        /* widget type                    */
    ID_SHOW_PERCENT,                         /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_BUTTON_PUSHED|GX_STYLE_BUTTON_TOGGLE|GX_STYLE_TEXT_LEFT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_CHECKBOX),                     /* control block size             */
    GX_COLOR_ID_RED,                         /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_RED,                         /* disabled color id              */
    gx_studio_checkbox_create,               /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {340, 126, 478, 149},                    /* widget size                    */
    &progress_bar_window_checkbox_2_define,  /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PROGRESS_BAR_WINDOW_CONTROL_BLOCK, progress_bar_window_checkbox_1), /* control block */
    (void *) &progress_bar_window_checkbox_1_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET progress_bar_window_checkbox_define =
{
    "checkbox",
    GX_TYPE_CHECKBOX,                        /* widget type                    */
    ID_SHOW_TEXT,                            /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_BUTTON_PUSHED|GX_STYLE_BUTTON_TOGGLE|GX_STYLE_TEXT_LEFT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_CHECKBOX),                     /* control block size             */
    GX_COLOR_ID_RED,                         /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_RED,                         /* disabled color id              */
    gx_studio_checkbox_create,               /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {340, 92, 453, 115},                     /* widget size                    */
    &progress_bar_window_checkbox_1_define,  /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PROGRESS_BAR_WINDOW_CONTROL_BLOCK, progress_bar_window_checkbox), /* control block */
    (void *) &progress_bar_window_checkbox_properties /* extended properties   */
};

GX_CONST GX_STUDIO_WIDGET progress_bar_window_icon_4_define =
{
    "icon_4",
    GX_TYPE_ICON,                            /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_HALIGN_LEFT|GX_STYLE_VALIGN_TOP,   /* style flags */
    0,                                       /* status flags                   */
    sizeof(GX_ICON),                         /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_WIDGET_FILL,                 /* disabled color id              */
    gx_studio_icon_create,                   /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {244, 395, 253, 416},                    /* widget size                    */
    &progress_bar_window_checkbox_define,    /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PROGRESS_BAR_WINDOW_CONTROL_BLOCK, progress_bar_window_icon_4), /* control block */
    (void *) &progress_bar_window_icon_4_properties /* extended properties     */
};

GX_CONST GX_STUDIO_WIDGET progress_bar_window_icon_3_define =
{
    "icon_3",
    GX_TYPE_ICON,                            /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_HALIGN_LEFT|GX_STYLE_VALIGN_TOP,   /* style flags */
    0,                                       /* status flags                   */
    sizeof(GX_ICON),                         /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_WIDGET_FILL,                 /* disabled color id              */
    gx_studio_icon_create,                   /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {53, 395, 62, 416},                      /* widget size                    */
    &progress_bar_window_icon_4_define,      /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PROGRESS_BAR_WINDOW_CONTROL_BLOCK, progress_bar_window_icon_3), /* control block */
    (void *) &progress_bar_window_icon_3_properties /* extended properties     */
};

GX_CONST GX_STUDIO_WIDGET progress_bar_window_pixelmap_slider_define =
{
    "pixelmap_slider",
    GX_TYPE_PIXELMAP_SLIDER,                 /* widget type                    */
    ID_POS,                                  /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_ENABLED|GX_STYLE_TILE_BACKGROUND,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PIXELMAP_SLIDER),              /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_WIDGET_FILL,                 /* selected color id              */
    GX_COLOR_ID_WIDGET_FILL,                 /* disabled color id              */
    gx_studio_pixelmap_slider_create,        /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {63, 387, 243, 425},                     /* widget size                    */
    &progress_bar_window_icon_3_define,      /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PROGRESS_BAR_WINDOW_CONTROL_BLOCK, progress_bar_window_pixelmap_slider), /* control block */
    (void *) &progress_bar_window_pixelmap_slider_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET progress_bar_window_define =
{
    "progress_bar_window",
    GX_TYPE_WINDOW,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TILE_WALLPAPER,   /* style flags             */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(PROGRESS_BAR_WINDOW_CONTROL_BLOCK), /* control block size           */
    GX_COLOR_ID_RED,                         /* normal color id                */
    GX_COLOR_ID_RED,                         /* selected color id              */
    GX_COLOR_ID_RED,                         /* disabled color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    (UINT (*)(GX_WIDGET *, GX_EVENT *)) window_event_handle, /* event function override */
    {0, 0, 639, 479},                        /* widget size                    */
    GX_NULL,                                 /* next widget                    */
    &progress_bar_window_pixelmap_slider_define, /* child widget               */
    0,                                       /* control block                  */
    (void *) &progress_bar_window_properties /* extended properties            */
};
GX_CONST GX_STUDIO_WIDGET_ENTRY radial_progress_bar_widget_table[] =
{
    { &progress_bar_window_define, (GX_WIDGET *) &progress_bar_window },
    {GX_NULL, GX_NULL}
};

UINT gx_studio_named_widget_create(char *name, GX_WIDGET *parent, GX_WIDGET **new_widget)
{
    return gx_studio_named_widget_create_from_table(name, parent, new_widget, radial_progress_bar_widget_table);
}

UINT gx_studio_display_configure(USHORT display, UINT (*driver)(GX_DISPLAY *),
    GX_UBYTE language, USHORT theme, GX_WINDOW_ROOT **return_root)
{
    GX_STUDIO_DISPLAY_INFO *display_info = &radial_progress_bar_display_table[display];
    return gx_studio_display_config(display_info, driver, language, theme, return_root);
}
#undef GUIX_STUDIO_GENERATED_FILE
