/***************************************************************************
 * Copyright (c) 2024 Microsoft Corporation
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * SPDX-License-Identifier: MIT
 **************************************************************************/

/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  specification file(s). For more information please refer to the Azure RTOS */
/*  GUIX Studio User Guide, or visit our web site at azure.com/rtos            */
/*                                                                             */
/*  GUIX Studio Revision 6.1.12.0                                              */
/*  Date (dd.mm.yyyy): 25. 8.2022   Time (hh:mm): 18:44                        */
/*******************************************************************************/


#ifndef _DEMO_GUIX_TRANSITIONS_SPECIFICATIONS_H_
#define _DEMO_GUIX_TRANSITIONS_SPECIFICATIONS_H_

#include "gx_studio_widget.h"

/* Define widget ids                                                           */

#define IDB_CLOSE 1
#define IDB_INFO 2
#define IDB_SETTINGS 3


/* Define animation ids                                                        */

#define ANIMATION_ABOUT_FADE_IN 1
#define ANIMATION_ABOUT_FADE_OUT 2
#define GX_NEXT_ANIMATION_ID 3


/* Define user event ids                                                       */

#define GX_NEXT_USER_EVENT_ID GX_FIRST_USER_EVENT


/* Declare top-level control blocks                                            */

struct PHOTO_3_CONTROL_BLOCK : public GX_WINDOW
{
};

struct PHOTO_2_CONTROL_BLOCK : public GX_WINDOW
{
};

struct PHOTO_1_CONTROL_BLOCK : public GX_WINDOW
{
};

struct SETTINGS_WIN_CONTROL_BLOCK : public GX_WINDOW
{
    GX_PIXELMAP_BUTTON settings_win_close_button;
    GX_ICON settings_win_icon;
    GX_ICON settings_win_icon_2;
    GX_PROMPT settings_win_prompt;
    GX_CHECKBOX settings_win_checkbox;
    GX_CHECKBOX settings_win_checkbox_1;
    GX_CHECKBOX settings_win_checkbox_2;
    GX_CHECKBOX settings_win_checkbox_3;
    GX_CHECKBOX settings_win_checkbox_4;
    GX_CHECKBOX settings_win_checkbox_5;
    GX_CHECKBOX settings_win_checkbox_6;
    GX_CHECKBOX settings_win_checkbox_7;
};

struct BACKGROUND_WIN_CONTROL_BLOCK : public GX_WINDOW
{
    GX_ICON background_win_logo;
    GX_PIXELMAP_BUTTON background_win_info_button;
    GX_ICON background_win_icon_7;
    GX_PIXELMAP_BUTTON background_win_settings_button;
    GX_ICON background_win_icon_8;
    GX_WINDOW background_win_child_frame;
    GX_PROMPT background_win_prompt_1;
    GX_PROMPT background_win_prompt;
};

struct ABOUT_WIN_CONTROL_BLOCK : public GX_WINDOW
{
    GX_PIXELMAP_BUTTON about_win_close_button;
    GX_ICON about_win_icon;
    GX_ICON about_win_icon_2;
    GX_ICON about_win_icon_4;
    GX_ICON about_win_icon_1;
};


/* extern statically defined control blocks                                    */

#ifndef GUIX_STUDIO_GENERATED_FILE
extern PHOTO_3_CONTROL_BLOCK photo_3;
extern PHOTO_2_CONTROL_BLOCK photo_2;
extern PHOTO_1_CONTROL_BLOCK photo_1;
extern SETTINGS_WIN_CONTROL_BLOCK settings_win;
extern BACKGROUND_WIN_CONTROL_BLOCK background_win;
extern ABOUT_WIN_CONTROL_BLOCK about_win;
#endif

/* Declare event process functions, draw functions, and callback functions     */

UINT settings_win_event_process(GX_WINDOW *widget, GX_EVENT *event_ptr);
UINT BackgroundWinEventProcess(GX_WINDOW *widget, GX_EVENT *event_ptr);


/* Declare Studio-generated functions for creating top-level widgets           */

UINT gx_studio_named_widget_create(char *name, GX_WIDGET *parent, GX_WIDGET **new_widget);
UINT gx_studio_display_configure(USHORT display, UINT (*driver)(GX_DISPLAY *), GX_UBYTE language, USHORT theme, GX_WINDOW_ROOT **return_root);

#endif                                       /* sentry                         */
