/***************************************************************************
 * Copyright (c) 2024 Microsoft Corporation
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * SPDX-License-Identifier: MIT
 **************************************************************************/

/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  specification file(s). For more information please refer to the Azure RTOS */
/*  GUIX Studio User Guide, or visit our web site at azure.com/rtos            */
/*                                                                             */
/*  GUIX Studio Revision 6.3.0.0 (Preview)                                     */
/*  Date (dd.mm.yyyy):  4. 9.2023   Time (hh:mm): 11:04                        */
/*******************************************************************************/


#ifndef _STANDALONE_BINRES_LOAD_EXTENDED_UNICODE_32BPP_SPECIFICATIONS_H_
#define _STANDALONE_BINRES_LOAD_EXTENDED_UNICODE_32BPP_SPECIFICATIONS_H_

#include "gx_studio_widget.h"

/* Define widget ids                                                           */

#define ID_TEXT_8BPP 1
#define ID_TEXT_1BPP 2
#define ID_TEXT_4BPP 3
#define ID_FISH 4
#define ID_APPLE 5


/* Define animation ids                                                        */

#define GX_NEXT_ANIMATION_ID 1


/* Define user event ids                                                       */

#define GX_NEXT_USER_EVENT_ID GX_FIRST_USER_EVENT


/* Declare top-level control blocks                                            */

struct MAIN_SCREEN_CONTROL_BLOCK : public GX_WINDOW
{
    GX_PROMPT main_screen_text_8bpp;
    GX_PROMPT main_screen_text_1bpp;
    GX_PROMPT main_screen_text_4bpp;
    GX_WINDOW main_screen_pixelmap_fish;
    GX_WINDOW main_screen_pixelmap_apple;
};


/* extern statically defined control blocks                                    */

#ifndef GUIX_STUDIO_GENERATED_FILE
extern MAIN_SCREEN_CONTROL_BLOCK main_screen;
#endif

/* Declare event process functions, draw functions, and callback functions     */

VOID text_draw(GX_PROMPT *widget);
VOID pixelmap_draw(GX_WINDOW *widget);


/* Declare Studio-generated functions for creating top-level widgets           */

UINT gx_studio_named_widget_create(char *name, GX_WIDGET *parent, GX_WIDGET **new_widget);
UINT gx_studio_display_configure(USHORT display, UINT (*driver)(GX_DISPLAY *), GX_UBYTE language, USHORT theme, GX_WINDOW_ROOT **return_root);

#endif                                       /* sentry                         */
