/***************************************************************************
 * Copyright (c) 2024 Microsoft Corporation
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * SPDX-License-Identifier: MIT
 **************************************************************************/

/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  specification file(s). For more information please refer to the Azure RTOS */
/*  GUIX Studio User Guide, or visit our web site at azure.com/rtos            */
/*                                                                             */
/*  GUIX Studio Revision 6.1.12.0                                              */
/*  Date (dd.mm.yyyy): 25. 8.2022   Time (hh:mm): 18:23                        */
/*******************************************************************************/


#define GUIX_STUDIO_GENERATED_FILE
#include <stddef.h>
#include "guix_thermostat_resources.h"
#include "guix_thermostat_specifications.h"

THERMOMETER_SCREEN_CONTROL_BLOCK thermometer_screen;
GX_DISPLAY main_display_control_block;
GX_WINDOW_ROOT main_display_root_window;
GX_CANVAS  main_display_canvas_control_block;
ULONG      main_display_canvas_memory[153600];

extern GX_CONST GX_THEME *main_display_theme_table[];
extern GX_CONST GX_STRING *main_display_language_table[];

GX_STUDIO_DISPLAY_INFO guix_thermostat_display_table[1] =
{
    {
    "main_display",
    "main_display_canvas",
    main_display_theme_table,
    main_display_language_table,
    MAIN_DISPLAY_THEME_TABLE_SIZE,
    MAIN_DISPLAY_LANGUAGE_TABLE_SIZE,
    MAIN_DISPLAY_STRING_TABLE_SIZE,
    640,                                     /* x resolution                   */
    480,                                     /* y resolution                   */
    &main_display_control_block,
    &main_display_canvas_control_block,
    &main_display_root_window,
    main_display_canvas_memory,              /* canvas memory area             */
    614400,                                  /* canvas memory size in bytes    */
    GX_SCREEN_ROTATION_NONE                  /* rotation angle                 */
    }
};


GX_WINDOW_PROPERTIES thermometer_screen_properties =
{
    0                                        /* wallpaper pixelmap id          */
};
GX_CIRCULAR_GAUGE_PROPERTIES thermometer_screen_gauge_properties =
{
    0,                                       /* start angle                    */
    0,                                       /* animation steps                */
    0,                                       /* animation delay                */
    111,                                     /* needle xpos                    */
    113,                                     /* needle yos                     */
    69,                                      /* needle xcor                    */
    76,                                      /* needle ycor                    */
    GX_PIXELMAP_ID_BACKGROUND,               /* normal pixelmap id             */
    0,                                       /* selected pixelmap id           */
    GX_PIXELMAP_ID_NEEDLE                    /* needle pixelmap id             */
};
GX_PROMPT_PROPERTIES thermometer_screen_value_prompt_properties =
{
    GX_STRING_ID_STRING_5,                   /* string id                      */
    GX_FONT_ID_LARGE_BOLD,                   /* font id                        */
    GX_COLOR_ID_TEXT_INPUT_TEXT,             /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected text color            */
    GX_COLOR_ID_TEXT_INPUT_TEXT              /* disabled text color            */
};
GX_PROMPT_PROPERTIES thermometer_screen_prompt_properties =
{
    GX_STRING_ID_STRING_7,                   /* string id                      */
    GX_FONT_ID_BOLD,                         /* font id                        */
    GX_COLOR_ID_TEXT_INPUT_FILL,             /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected text color            */
    GX_COLOR_ID_TEXT_INPUT_FILL              /* disabled text color            */
};
GX_PROMPT_PROPERTIES thermometer_screen_prompt_1_properties =
{
    GX_STRING_ID_STRING_2,                   /* string id                      */
    GX_FONT_ID_MIDDLE,                       /* font id                        */
    GX_COLOR_ID_GREEN,                       /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected text color            */
    GX_COLOR_ID_GREEN                        /* disabled text color            */
};
GX_ICON_PROPERTIES thermometer_screen_icon_1_properties =
{
    GX_PIXELMAP_ID_MS_AZURE_LOGO_SMALL,      /* normal pixelmap id             */
    0                                        /* selected pixelmap id           */
};
GX_PIXELMAP_BUTTON_PROPERTIES thermometer_screen_minus_button_properties =
{
    GX_PIXELMAP_ID_BUTTON,                   /* normal pixelmap id             */
    GX_PIXELMAP_ID_BUTTON_ACTIVE,            /* selected pixelmap id           */
    0                                        /* disabled pixelmap id           */
};
GX_PIXELMAP_BUTTON_PROPERTIES thermometer_screen_plus_button_properties =
{
    GX_PIXELMAP_ID_BUTTON,                   /* normal pixelmap id             */
    GX_PIXELMAP_ID_BUTTON_ACTIVE,            /* selected pixelmap id           */
    0                                        /* disabled pixelmap id           */
};

GX_CONST GX_STUDIO_WIDGET thermometer_screen_prompt_define =
{
    "prompt",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_TEXT_CENTER,   /* style flags */
    0,                                       /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_WIDGET_FILL,                 /* disabled color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {345, 225, 366, 258},                    /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(THERMOMETER_SCREEN_CONTROL_BLOCK, thermometer_screen_prompt), /* control block */
    (void *) &thermometer_screen_prompt_properties /* extended properties      */
};

GX_CONST GX_STUDIO_WIDGET thermometer_screen_value_prompt_define =
{
    "value_prompt",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_TEXT_CENTER,   /* style flags */
    0,                                       /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_WIDGET_FILL,                 /* disabled color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {286, 233, 342, 277},                    /* widget size                    */
    &thermometer_screen_prompt_define,       /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(THERMOMETER_SCREEN_CONTROL_BLOCK, thermometer_screen_value_prompt), /* control block */
    (void *) &thermometer_screen_value_prompt_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET thermometer_screen_plus_button_define =
{
    "plus_button",
    GX_TYPE_PIXELMAP_BUTTON,                 /* widget type                    */
    ID_PLUS_BTN,                             /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED|GX_STYLE_BUTTON_REPEAT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PIXELMAP_BUTTON),              /* control block size             */
    GX_COLOR_ID_BTN_UPPER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_UPPER,                   /* disabled color id              */
    gx_studio_pixelmap_button_create,        /* create function                */
    (VOID (*)(GX_WIDGET *)) custom_pixelmap_button_draw, /* drawing function override */
    GX_NULL,                                 /* event function override        */
    {316, 382, 419, 445},                    /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(THERMOMETER_SCREEN_CONTROL_BLOCK, thermometer_screen_plus_button), /* control block */
    (void *) &thermometer_screen_plus_button_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET thermometer_screen_minus_button_define =
{
    "minus_button",
    GX_TYPE_PIXELMAP_BUTTON,                 /* widget type                    */
    ID_MINUS_BTN,                            /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED|GX_STYLE_BUTTON_REPEAT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PIXELMAP_BUTTON),              /* control block size             */
    GX_COLOR_ID_BTN_UPPER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_UPPER,                   /* disabled color id              */
    gx_studio_pixelmap_button_create,        /* create function                */
    (VOID (*)(GX_WIDGET *)) custom_pixelmap_button_draw, /* drawing function override */
    GX_NULL,                                 /* event function override        */
    {212, 382, 315, 445},                    /* widget size                    */
    &thermometer_screen_plus_button_define,  /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(THERMOMETER_SCREEN_CONTROL_BLOCK, thermometer_screen_minus_button), /* control block */
    (void *) &thermometer_screen_minus_button_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET thermometer_screen_icon_1_define =
{
    "icon_1",
    GX_TYPE_ICON,                            /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_HALIGN_LEFT|GX_STYLE_VALIGN_TOP,   /* style flags */
    0,                                       /* status flags                   */
    sizeof(GX_ICON),                         /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_WIDGET_FILL,                 /* disabled color id              */
    gx_studio_icon_create,                   /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {20, 20, 208, 49},                       /* widget size                    */
    &thermometer_screen_minus_button_define, /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(THERMOMETER_SCREEN_CONTROL_BLOCK, thermometer_screen_icon_1), /* control block */
    (void *) &thermometer_screen_icon_1_properties /* extended properties      */
};

GX_CONST GX_STUDIO_WIDGET thermometer_screen_prompt_1_define =
{
    "prompt_1",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_TEXT_CENTER,   /* style flags */
    0,                                       /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_WIDGET_FILL,                 /* disabled color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {149, 89, 511, 117},                     /* widget size                    */
    &thermometer_screen_icon_1_define,       /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(THERMOMETER_SCREEN_CONTROL_BLOCK, thermometer_screen_prompt_1), /* control block */
    (void *) &thermometer_screen_prompt_1_properties /* extended properties    */
};

GX_CONST GX_STUDIO_WIDGET thermometer_screen_gauge_define =
{
    "gauge",
    GX_TYPE_CIRCULAR_GAUGE,                  /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_CIRCULAR_GAUGE),               /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_WIDGET_FILL,                 /* disabled color id              */
    gx_studio_circular_gauge_create,         /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {207, 138, 426, 357},                    /* widget size                    */
    &thermometer_screen_prompt_1_define,     /* next widget definition         */
    &thermometer_screen_value_prompt_define, /* child widget definition        */
    offsetof(THERMOMETER_SCREEN_CONTROL_BLOCK, thermometer_screen_gauge), /* control block */
    (void *) &thermometer_screen_gauge_properties /* extended properties       */
};

GX_CONST GX_STUDIO_WIDGET thermometer_screen_define =
{
    "thermometer_screen",
    GX_TYPE_WINDOW,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE,                    /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(THERMOMETER_SCREEN_CONTROL_BLOCK), /* control block size            */
    GX_COLOR_ID_TEXT,                        /* normal color id                */
    GX_COLOR_ID_TEXT,                        /* selected color id              */
    GX_COLOR_ID_TEXT,                        /* disabled color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    (UINT (*)(GX_WIDGET *, GX_EVENT *)) thermo_screen_event_handler, /* event function override */
    {0, 0, 639, 479},                        /* widget size                    */
    GX_NULL,                                 /* next widget                    */
    &thermometer_screen_gauge_define,        /* child widget                   */
    0,                                       /* control block                  */
    (void *) &thermometer_screen_properties  /* extended properties            */
};
GX_CONST GX_STUDIO_WIDGET_ENTRY guix_thermostat_widget_table[] =
{
    { &thermometer_screen_define, (GX_WIDGET *) &thermometer_screen },
    {GX_NULL, GX_NULL}
};

UINT gx_studio_named_widget_create(char *name, GX_WIDGET *parent, GX_WIDGET **new_widget)
{
    return gx_studio_named_widget_create_from_table(name, parent, new_widget, guix_thermostat_widget_table);
}

UINT gx_studio_display_configure(USHORT display, UINT (*driver)(GX_DISPLAY *),
    GX_UBYTE language, USHORT theme, GX_WINDOW_ROOT **return_root)
{
    GX_STUDIO_DISPLAY_INFO *display_info = &guix_thermostat_display_table[display];
    return gx_studio_display_config(display_info, driver, language, theme, return_root);
}
#undef GUIX_STUDIO_GENERATED_FILE
