/***************************************************************************
 * Copyright (c) 2024 Microsoft Corporation
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * SPDX-License-Identifier: MIT
 **************************************************************************/

/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  specification file(s). For more information please refer to the Azure RTOS */
/*  GUIX Studio User Guide, or visit our web site at azure.com/rtos            */
/*                                                                             */
/*  GUIX Studio Revision 6.3.0.0                                               */
/*  Date (dd.mm.yyyy): 24.11.2023   Time (hh:mm): 16:43                        */
/*******************************************************************************/


#ifndef _GUIX_WIDGET_TYPES_SPECIFICATIONS_H_
#define _GUIX_WIDGET_TYPES_SPECIFICATIONS_H_

#include "gx_studio_widget.h"

/* Define widget ids                                                           */

#define ID_MENU_SCREEN 1
#define ID_SCROLL_WHEEL_SCREEN 2
#define ID_SCROLL_WHEEL_DAY 3
#define ID_SCROLL_WHEEL_YEAR 4
#define ID_SCROLL_WHEEL_MONTH 5
#define IDB_NEXT 6
#define ID_GAUGE_SCREEN 7
#define ID_GAUGE_ANIMATED 8
#define ID_PROMPT_ANIMATED 9
#define ID_SLIDER_ANIMATED 10
#define ID_SLIDER_NOT_ANIMATED 11
#define ID_GAUGE_NOT_ANIMATED 12
#define ID_PROMPT_NOT_ANIMATED 13
#define ID_WINDOW_SCREEN 14
#define ID_NESTED_WINDOW_BLUE 15
#define ID_VERTICAL_LIST 16
#define ID_HORIZONTAL_LIST 17
#define ICON_BUTTON_DISC 18
#define ICON_BUTTON_USER 19
#define ICON_BUTTON_PEN 20
#define ICON_BUTTON_TRASH 21
#define ICON_BUTTON_COG 22
#define ID_DROP_LIST 23
#define ID_SLIDER_SCREEN 24
#define ID_PIXELMAP_SLIDER_H 25
#define ID_PIXELMAP_SLIDER_V 26
#define ID_PIXELMAP_SLIDER_THIN_H 27
#define ID_PROGRESS_BAR 28
#define ID_PROGRESS_BAR_PROMPT 29
#define ID_TEXT_SCREEN 30
#define ID_BUTTON_SCREEN 31
#define IDB_CHECKBOX 32


/* Define animation ids                                                        */

#define GX_NEXT_ANIMATION_ID 1


/* Define user event ids                                                       */

#define GX_NEXT_USER_EVENT_ID GX_FIRST_USER_EVENT


/* Declare top-level control blocks                                            */

struct BASE_SCREEN_CONTROL_BLOCK : public GX_WINDOW
{
    GX_ICON Base_Screen_Icon_EL_Logo;
    GX_PIXELMAP_BUTTON Base_Screen_Next_Button;
};

struct GAUGE_SCREEN_CONTROL_BLOCK : public BASE_SCREEN_CONTROL_BLOCK
{
    GX_PROMPT Gauge_Screen_Prompt_Circular_Gauges;
    GX_CIRCULAR_GAUGE Gauge_Screen_Gauge_Animated;
    GX_PROMPT Gauge_Screen_prompt_animated;
    GX_PIXELMAP_SLIDER Gauge_Screen_Pixelmap_Slider_Animated;
    GX_PIXELMAP_SLIDER Gauge_Screen_Pixelmap_Slider_Not_Animated;
    GX_PROMPT Gauge_Screen_Prompt_Animated;
    GX_PROMPT Gauge_Screen_Prompt_Not_Animated;
    GX_CIRCULAR_GAUGE Gauge_Screen_Gauge_Not_Animated;
    GX_PROMPT Gauge_Screen_prompt_not_animated;
};

struct WINDOW_SCREEN_CONTROL_BLOCK : public BASE_SCREEN_CONTROL_BLOCK
{
    GX_PROMPT Window_Screen_Prompt_Nested_Windows;
    GX_PROMPT Window_Screen_Prompt_Scollable_Frame;
    GX_WINDOW Window_Screen_Nested_Window_BG;
    GX_WINDOW Window_Screen_Nested_Window_Blue;
    GX_WINDOW Window_Screen_nest_window;
    GX_WINDOW Window_Screen_Scrollable_Frame_BG;
    GX_WINDOW Window_Screen_Scrollable_Frame_Sky;
    GX_SCROLLBAR Window_Screen_Hscroll;
    GX_SCROLLBAR Window_Screen_Vertical_Scroll;
    GX_PROMPT Window_Screen_Prompt_Vertical_List;
    GX_PROMPT Window_Screen_Prompt_Horizontal_List;
    GX_VERTICAL_LIST Window_Screen_Vertical_List;
    GX_WINDOW Window_Screen_window_6;
    GX_TEXT_BUTTON Window_Screen_button_1;
    GX_WINDOW Window_Screen_window_8;
    GX_TEXT_BUTTON Window_Screen_button_3;
    GX_WINDOW Window_Screen_window_7;
    GX_TEXT_BUTTON Window_Screen_button_2;
    GX_HORIZONTAL_LIST Window_Screen_Horizontal_List;
    GX_WINDOW Window_Screen_window_5;
    GX_ICON_BUTTON Window_Screen_icon_button_1;
    GX_WINDOW Window_Screen_window_9;
    GX_ICON_BUTTON Window_Screen_icon_button_2;
    GX_WINDOW Window_Screen_window_10;
    GX_ICON_BUTTON Window_Screen_icon_button_3;
    GX_WINDOW Window_Screen_window_11;
    GX_ICON_BUTTON Window_Screen_icon_button_4;
    GX_WINDOW Window_Screen_window_12;
    GX_ICON_BUTTON Window_Screen_icon_button_5;
    GX_DROP_LIST Window_Screen_Drop_List;
    GX_PIXELMAP_BUTTON Window_Screen_Drop_List_Button;
    GX_PROMPT Window_Screen_Prompt_Drop_List;
};

struct SLIDER_SCREEN_CONTROL_BLOCK : public BASE_SCREEN_CONTROL_BLOCK
{
    GX_PROMPT Slider_Screen_Prompt_Various_Sliders;
    GX_PIXELMAP_SLIDER Slider_Screen_Pixelmap_Slider_H;
    GX_PIXELMAP_SLIDER Slider_Screen_Pixelmap_Slider_V;
    GX_PIXELMAP_SLIDER Slider_Screen_Pixelmap_Slider_Thin_H;
    GX_PIXELMAP_SLIDER Slider_Screen_Pixelmap_Slider_Thin_V;
    GX_WINDOW Slider_Screen_Progress_Bar_BG;
    GX_PROGRESS_BAR Slider_Screen_Progress_Bar;
    GX_PROMPT Slider_Screen_Progress_Bar_Prompt;
    GX_PIXELMAP_SLIDER Slider_Screen_Pixelmap_Slider_Red;
    GX_ICON Slider_Screen_Icon_Red_Top;
    GX_ICON Slider_Screen_Icon_Red_Bottom;
    GX_PIXELMAP_SLIDER Slider_Screen_Pixelmap_Slider_Green;
    GX_ICON Slider_Screen_Icon_Green_Top;
    GX_ICON Slider_Screen_Icon_Green_Bottom;
    GX_PIXELMAP_SLIDER Slider_Screen_Pixlemap_Slider_Orange;
    GX_ICON Slider_Screen_Icon_Orange_Bottom;
    GX_ICON Slider_Screen_Icon_Orange_Top;
};

struct TEXT_SCREEN_CONTROL_BLOCK : public BASE_SCREEN_CONTROL_BLOCK
{
    GX_PROMPT Text_Screen_Prompt_Texts;
    GX_PROMPT Text_Screen_Prompt_Transparent_Thin_Border;
    GX_PROMPT Text_Screen_Prompt_Transparent_No_Border;
    GX_PROMPT Text_Screen_Prompt_Transparent_Thick_Border;
    GX_PIXELMAP_PROMPT Text_Screen_Pixelmap_Prompt;
    GX_MULTI_LINE_TEXT_VIEW Text_Screen_ML_Text_View;
    GX_MULTI_LINE_TEXT_INPUT Text_Screen_ML_Text_Input;
    GX_SINGLE_LINE_TEXT_INPUT Text_Screen_text_input;
    GX_NUMERIC_PROMPT Text_Screen_numeric_prompt;
    GX_NUMERIC_PIXELMAP_PROMPT Text_Screen_numeric_pixelmap_prompt;
    GX_RICH_TEXT_VIEW Text_Screen_ML_Text_Rich_View;
};

struct BUTTON_SCREEN_CONTROL_BLOCK : public BASE_SCREEN_CONTROL_BLOCK
{
    GX_PROMPT Button_Screen_Prompt_Button;
    GX_PROMPT Button_Screen_Prompt_GX_BUTTON;
    GX_PROMPT Button_Screen_Prompt_GX_TEXT_BUTTON;
    GX_PROMPT Button_Screen_Prompt_GX_MULTI_LINE_TEXT_BUTTON;
    GX_PIXELMAP_BUTTON Button_Screen_Pixelmap_Button;
    GX_PROMPT Button_Screen_Prompt_GX_PIXELMAP_BUTTON;
    GX_ICON Button_Screen_Icon;
    GX_PROMPT Button_Screen_Prompt_GX_ICON_BUTTON;
    GX_PROMPT Button_Screen_Prompt_GX_CHECKBOX;
    GX_PROMPT Button_Screen_Prompt_GX_RADIO_BUTTON;
    GX_CHECKBOX Button_Screen_Checkbox;
    GX_RADIO_BUTTON Button_Screen_Radio_Button_Off;
    GX_RADIO_BUTTON Button_Screen_Radio_Button_On;
    GX_ICON_BUTTON Button_Screen_Icon_Button;
    GX_TEXT_BUTTON Button_Screen_Text_Button;
    GX_BUTTON Button_Screen_Button;
    GX_MULTI_LINE_TEXT_BUTTON Button_Screen_Multi_Line_Button;
};

struct MENU_SCREEN_CONTROL_BLOCK : public BASE_SCREEN_CONTROL_BLOCK
{
    GX_PROMPT Menu_Screen_title;
    GX_ACCORDION_MENU Menu_Screen_accordion;
    GX_MENU Menu_Screen_accordion_menu_1;
    GX_ACCORDION_MENU Menu_Screen_embedded_accordion;
    GX_MENU Menu_Screen_accordion_menu_1_1;
    GX_MULTI_LINE_TEXT_VIEW Menu_Screen_accordion_menu_1_1_1;
    GX_MENU Menu_Screen_accordion_menu_1_2;
    GX_PROMPT Menu_Screen_accordion_menu_1_2_1;
    GX_MENU Menu_Screen_accordion_menu_2;
    GX_MENU Menu_Screen_accordion_menu_2_1;
    GX_MENU Menu_Screen_accordion_menu_2_2;
    GX_MENU Menu_Screen_accordion_menu_3;
    GX_PROMPT Menu_Screen_accordion_menu_3_1;
    GX_PROMPT Menu_Screen_accordion_menu_3_2;
    GX_ICON Menu_Screen_accordion_menu_3_icon;
    GX_TREE_VIEW Menu_Screen_tree_view;
    GX_MENU Menu_Screen_tree_menu;
    GX_PROMPT Menu_Screen_tree_menu_1;
    GX_PROMPT Menu_Screen_tree_menu_1_1;
    GX_ICON Menu_Screen_icon;
    GX_MENU Menu_Screen_tree_menu_2;
    GX_MENU Menu_Screen_tree_menu_2_1;
    GX_PROMPT Menu_Screen_tree_menu_2_1_1;
    GX_PROMPT Menu_Screen_tree_menu_2_1_2;
    GX_ICON Menu_Screen_icon_1;
    GX_MENU Menu_Screen_tree_menu_2_2;
    GX_MENU Menu_Screen_tree_menu_2_2_1;
    GX_PROMPT Menu_Screen_tree_menu_2_2_1_1;
    GX_PROMPT Menu_Screen_tree_menu_2_2_1_2;
    GX_ICON Menu_Screen_icon_2;
    GX_ICON Menu_Screen_icon_3;
    GX_ICON Menu_Screen_icon_4;
    GX_MENU Menu_Screen_tree_menu_3;
    GX_PROMPT Menu_Screen_tree_menu_3_1;
    GX_ICON Menu_Screen_icon_5;
    GX_SCROLLBAR Menu_Screen_tree_hscroll;
    GX_SCROLLBAR Menu_Screen_tree_vscroll;
    GX_MENU Menu_Screen_tree_menu_4;
    GX_PROMPT Menu_Screen_prompt_10;
    GX_ICON Menu_Screen_icon_6;
    GX_PROMPT Menu_Screen_prompt;
    GX_PROMPT Menu_Screen_prompt_1;
};

struct SCROLL_WHEEL_SCREEN_CONTROL_BLOCK : public BASE_SCREEN_CONTROL_BLOCK
{
    GX_NUMERIC_SCROLL_WHEEL Scroll_Wheel_Screen_scroll_wheel_day;
    GX_NUMERIC_SCROLL_WHEEL Scroll_Wheel_Screen_scroll_wheel_year;
    GX_STRING_SCROLL_WHEEL Scroll_Wheel_Screen_scroll_wheel_month;
    GX_PROMPT Scroll_Wheel_Screen_Prompt_Circular_Gauges_1;
};


/* extern statically defined control blocks                                    */

#ifndef GUIX_STUDIO_GENERATED_FILE
extern MENU_SCREEN_CONTROL_BLOCK Menu_Screen;
extern SCROLL_WHEEL_SCREEN_CONTROL_BLOCK Scroll_Wheel_Screen;
extern BASE_SCREEN_CONTROL_BLOCK Base_Screen;
extern GAUGE_SCREEN_CONTROL_BLOCK Gauge_Screen;
extern WINDOW_SCREEN_CONTROL_BLOCK Window_Screen;
extern SLIDER_SCREEN_CONTROL_BLOCK Slider_Screen;
extern TEXT_SCREEN_CONTROL_BLOCK Text_Screen;
extern BUTTON_SCREEN_CONTROL_BLOCK Button_Screen;
#endif

/* Declare event process functions, draw functions, and callback functions     */

UINT scroll_wheel_screen_event_process(GX_WINDOW *widget, GX_EVENT *event_ptr);
UINT day_wheel_value_format(GX_NUMERIC_SCROLL_WHEEL *wheel, INT row, GX_STRING *string);
VOID custom_next_button_draw(GX_PIXELMAP_BUTTON *widget);
UINT gauge_window_event_handler(GX_WINDOW *widget, GX_EVENT *event_ptr);
UINT window_screen_event_handler(GX_WINDOW *widget, GX_EVENT *event_ptr);
VOID nested_parent_window_draw(GX_WINDOW *widget);
UINT scroll_frame_event_handler(GX_WINDOW *widget, GX_EVENT *event_ptr);
VOID scroll_frame_draw(GX_WINDOW *widget);
VOID custom_text_button_draw(GX_TEXT_BUTTON *widget);
VOID custom_icon_button_draw(GX_ICON_BUTTON *widget);
VOID drop_list_row_create(GX_VERTICAL_LIST *, GX_WIDGET *, INT);
UINT slider_screen_event_process(GX_WINDOW *widget, GX_EVENT *event_ptr);
UINT text_screen_event_handler(GX_WINDOW *widget, GX_EVENT *event_ptr);
VOID custom_transparent_prompt_thick_border_draw(GX_PROMPT *widget);
VOID numeric_prompt_format_func(GX_NUMERIC_PROMPT *, INT);
VOID numeric_pixelmap_prompt_format_func(GX_NUMERIC_PIXELMAP_PROMPT *, INT);
VOID custom_button_draw(GX_BUTTON *widget);
VOID custom_multi_line_text_button_draw(GX_MULTI_LINE_TEXT_BUTTON *widget);

/* Declare Studio-generated functions for creating top-level widgets           */

UINT gx_studio_named_widget_create(char *name, GX_WIDGET *parent, GX_WIDGET **new_widget);
UINT gx_studio_display_configure(USHORT display, UINT (*driver)(GX_DISPLAY *), GX_UBYTE language, USHORT theme, GX_WINDOW_ROOT **return_root);

#endif                                       /* sentry                         */
