/***************************************************************************
 * Copyright (c) 2024 Microsoft Corporation
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * SPDX-License-Identifier: MIT
 **************************************************************************/

/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  specification file(s). For more information please refer to the Azure RTOS */
/*  GUIX Studio User Guide, or visit our web site at azure.com/rtos            */
/*                                                                             */
/*  GUIX Studio Revision 6.2.0.1                                               */
/*  Date (dd.mm.yyyy): 31.10.2022   Time (hh:mm): 14:12                        */
/*******************************************************************************/


#define GUIX_STUDIO_GENERATED_FILE
#include <stddef.h>
#include "two_displays_MAIN_DISPLAY_resources.h"
#include "two_displays_SECONDARY_resources.h"
#include "two_displays_specifications.h"

MAIN_DISPLAY_MAIN_WINDOW_CONTROL_BLOCK MAIN_DISPLAY_main_window;
SECONDARY_MAIN_WINDOW_CONTROL_BLOCK SECONDARY_main_window;
GX_DISPLAY MAIN_DISPLAY_control_block;
GX_WINDOW_ROOT MAIN_DISPLAY_root_window;
GX_CANVAS  MAIN_DISPLAY_canvas_control_block;
ULONG      MAIN_DISPLAY_canvas_memory[38400];

GX_DISPLAY SECONDARY_control_block;
GX_WINDOW_ROOT SECONDARY_root_window;
GX_CANVAS  SECONDARY_canvas_control_block;
ULONG      SECONDARY_canvas_memory[38400];

extern GX_CONST GX_THEME *MAIN_DISPLAY_theme_table[];
extern GX_CONST GX_STRING *MAIN_DISPLAY_language_table[];
extern GX_CONST GX_THEME *SECONDARY_theme_table[];
extern GX_CONST GX_STRING *SECONDARY_language_table[];

GX_STUDIO_DISPLAY_INFO two_displays_display_table[2] =
{
    {
    "MAIN_DISPLAY",
    "MAIN_DISPLAY_canvas",
    MAIN_DISPLAY_theme_table,
    MAIN_DISPLAY_language_table,
    MAIN_DISPLAY_THEME_TABLE_SIZE,
    MAIN_DISPLAY_LANGUAGE_TABLE_SIZE,
    MAIN_DISPLAY_STRING_TABLE_SIZE,
    320,                                     /* x resolution                   */
    240,                                     /* y resolution                   */
    &MAIN_DISPLAY_control_block,
    &MAIN_DISPLAY_canvas_control_block,
    &MAIN_DISPLAY_root_window,
    MAIN_DISPLAY_canvas_memory,              /* canvas memory area             */
    153600,                                  /* canvas memory size in bytes    */
    0                                        /* rotation angle                 */
    },
    {
    "SECONDARY",
    "SECONDARY_canvas",
    SECONDARY_theme_table,
    SECONDARY_language_table,
    SECONDARY_THEME_TABLE_SIZE,
    SECONDARY_LANGUAGE_TABLE_SIZE,
    SECONDARY_STRING_TABLE_SIZE,
    320,                                     /* x resolution                   */
    240,                                     /* y resolution                   */
    &SECONDARY_control_block,
    &SECONDARY_canvas_control_block,
    &SECONDARY_root_window,
    SECONDARY_canvas_memory,                 /* canvas memory area             */
    153600,                                  /* canvas memory size in bytes    */
    0                                        /* rotation angle                 */
    }
};


GX_WINDOW_PROPERTIES MAIN_DISPLAY_main_window_properties =
{
    0                                        /* wallpaper pixelmap id          */
};
GX_ICON_PROPERTIES MAIN_DISPLAY_main_window_icon_1_properties =
{
    GX_PIXELMAP_ID_MAIN_DISPLAY_HOME,        /* normal pixelmap id             */
    0                                        /* selected pixelmap id           */
};
GX_PROMPT_PROPERTIES MAIN_DISPLAY_main_window_prompt_properties =
{
    GX_STRING_ID_MAIN_DISPLAY_STRING_2,      /* string id                      */
    GX_FONT_ID_PROMPT,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected text color            */
    GX_COLOR_ID_TEXT                         /* disabled text color            */
};

GX_CONST GX_STUDIO_WIDGET MAIN_DISPLAY_main_window_prompt_define =
{
    "prompt",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_TEXT_CENTER,   /* style flags */
    0,                                       /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_WIDGET_FILL,                 /* disabled color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {111, 42, 205, 59},                      /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */
    offsetof(MAIN_DISPLAY_MAIN_WINDOW_CONTROL_BLOCK, MAIN_DISPLAY_main_window_prompt), /* control block */
    (void *) &MAIN_DISPLAY_main_window_prompt_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET MAIN_DISPLAY_main_window_icon_1_define =
{
    "icon_1",
    GX_TYPE_ICON,                            /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED|GX_STYLE_HALIGN_LEFT|GX_STYLE_VALIGN_TOP,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON),                         /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_WIDGET_FILL,                 /* disabled color id              */
    gx_studio_icon_create,                   /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {137, 88, 176, 127},                     /* widget size                    */
    &MAIN_DISPLAY_main_window_prompt_define, /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */
    offsetof(MAIN_DISPLAY_MAIN_WINDOW_CONTROL_BLOCK, MAIN_DISPLAY_main_window_icon_1), /* control block */
    (void *) &MAIN_DISPLAY_main_window_icon_1_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET MAIN_DISPLAY_main_window_define =
{
    "MAIN_DISPLAY_main_window",
    GX_TYPE_WINDOW,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_THIN,                    /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(MAIN_DISPLAY_MAIN_WINDOW_CONTROL_BLOCK), /* control block size      */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_WINDOW_FILL,                 /* selected color id              */
    GX_COLOR_ID_WINDOW_FILL,                 /* disabled color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {24, 18, 290, 197},                      /* widget size                    */
    GX_NULL,                                 /* next widget                    */
    &MAIN_DISPLAY_main_window_icon_1_define, /* child widget                   */
    0,                                       /* control block                  */
    (void *) &MAIN_DISPLAY_main_window_properties /* extended properties       */
};
GX_WINDOW_PROPERTIES SECONDARY_main_window_properties =
{
    0                                        /* wallpaper pixelmap id          */
};
GX_ICON_BUTTON_PROPERTIES SECONDARY_main_window_icon_button_1_properties =
{
    GX_PIXELMAP_ID_SECONDARY_I_PATIENTLIST_LG  /* pixelmap id                  */
};
GX_PROMPT_PROPERTIES SECONDARY_main_window_prompt_properties =
{
    GX_STRING_ID_SECONDARY_STRING_2,         /* string id                      */
    GX_FONT_ID_PROMPT,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected text color            */
    GX_COLOR_ID_TEXT                         /* disabled text color            */
};

GX_CONST GX_STUDIO_WIDGET SECONDARY_main_window_prompt_define =
{
    "prompt",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_TEXT_CENTER,   /* style flags */
    0,                                       /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_WIDGET_FILL,                 /* disabled color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {71, 106, 150, 123},                     /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */
    offsetof(SECONDARY_MAIN_WINDOW_CONTROL_BLOCK, SECONDARY_main_window_prompt), /* control block */
    (void *) &SECONDARY_main_window_prompt_properties /* extended properties   */
};

GX_CONST GX_STUDIO_WIDGET SECONDARY_main_window_icon_button_1_define =
{
    "icon_button_1",
    GX_TYPE_ICON_BUTTON,                     /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED|GX_STYLE_HALIGN_CENTER|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON_BUTTON),                  /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_LOWER,                   /* disabled color id              */
    gx_studio_icon_button_create,            /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {87, 37, 128, 78},                       /* widget size                    */
    &SECONDARY_main_window_prompt_define,    /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */
    offsetof(SECONDARY_MAIN_WINDOW_CONTROL_BLOCK, SECONDARY_main_window_icon_button_1), /* control block */
    (void *) &SECONDARY_main_window_icon_button_1_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET SECONDARY_main_window_define =
{
    "SECONDARY_main_window",
    GX_TYPE_WINDOW,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_THIN,                    /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(SECONDARY_MAIN_WINDOW_CONTROL_BLOCK), /* control block size         */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_WINDOW_FILL,                 /* selected color id              */
    GX_COLOR_ID_WINDOW_FILL,                 /* disabled color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {37, 19, 185, 217},                      /* widget size                    */
    GX_NULL,                                 /* next widget                    */
    &SECONDARY_main_window_icon_button_1_define, /* child widget               */
    0,                                       /* control block                  */
    (void *) &SECONDARY_main_window_properties /* extended properties          */
};
GX_CONST GX_STUDIO_WIDGET_ENTRY two_displays_widget_table[] =
{
    { &MAIN_DISPLAY_main_window_define, (GX_WIDGET *) &MAIN_DISPLAY_main_window },
    { &SECONDARY_main_window_define, (GX_WIDGET *) &SECONDARY_main_window },
    {GX_NULL, GX_NULL}
};

UINT gx_studio_named_widget_create(char *name, GX_WIDGET *parent, GX_WIDGET **new_widget)
{
    return gx_studio_named_widget_create_from_table(name, parent, new_widget, two_displays_widget_table);
}

UINT gx_studio_display_configure(USHORT display, UINT (*driver)(GX_DISPLAY *),
    GX_UBYTE language, USHORT theme, GX_WINDOW_ROOT **return_root)
{
    GX_STUDIO_DISPLAY_INFO *display_info = &two_displays_display_table[display];
    return gx_studio_display_config(display_info, driver, language, theme, return_root);
}
#undef GUIX_STUDIO_GENERATED_FILE
