/***************************************************************************
 * Copyright (c) 2024 Microsoft Corporation
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * SPDX-License-Identifier: MIT
 **************************************************************************/

/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  specification file(s). For more information please refer to the Azure RTOS */
/*  GUIX Studio User Guide, or visit our web site at azure.com/rtos            */
/*                                                                             */
/*  GUIX Studio Revision 6.1.12.0                                              */
/*  Date (dd.mm.yyyy): 25. 8.2022   Time (hh:mm): 18:23                        */
/*******************************************************************************/


#ifndef _DEMO_GUIX_WASHING_MACHINE_SPECIFICATIONS_H_
#define _DEMO_GUIX_WASHING_MACHINE_SPECIFICATIONS_H_

#include "gx_studio_widget.h"

/* Define widget ids                                                           */

#define ID_BTN_QUICK 1
#define ID_BTN_DEEP 2
#define ID_BTN_QUICK_SMALL 3
#define ID_BTN_DEEP_SMALL 4
#define ID_BTN_ECO 5
#define ID_BTN_ECO_SMALL 6
#define ID_WATER_LEVEL_SLIDER 7
#define ID_BTN_MAX 8
#define ID_BTN_HIGH 9
#define ID_BTN_MEDIUM 10
#define ID_BTN_LOW 11
#define ID_BTN_MIN 12
#define ID_TEMPERATURE_SLIDER 13
#define ID_WASH_CYCLE_SLIDER 14
#define ID_BTN_WASH_CYCLE 15
#define ID_BTN_TEMPERATURE 16
#define ID_BTN_WATER_LEVEL 17
#define ID_BTN_PLAY 18


/* Define animation ids                                                        */

#define GX_NEXT_ANIMATION_ID 1


/* Define user event ids                                                       */

#define GX_NEXT_USER_EVENT_ID GX_FIRST_USER_EVENT


/* Declare top-level control blocks                                            */

struct TEMPLATE_MODE_BTN_SMALL_CONTROL_BLOCK : public GX_PIXELMAP_BUTTON
{
    GX_PROMPT template_mode_btn_small_mode_label;
    GX_PROMPT template_mode_btn_small_mode_label_4;
    GX_NUMERIC_PROMPT template_mode_btn_small_total_time;
    GX_PROMPT template_mode_btn_small_mode_label_5;
};

struct TEMPLATE_MODE_BTN_CONTROL_BLOCK : public GX_PIXELMAP_BUTTON
{
    GX_PROMPT template_mode_btn_mode_label;
    GX_PROMPT template_mode_btn_wash_label;
    GX_PROMPT template_mode_btn_min_label;
    GX_NUMERIC_PROMPT template_mode_btn_total_time;
    GX_RADIAL_PROGRESS_BAR template_mode_btn_mode_progress_bar;
    GX_NUMERIC_PROMPT template_mode_btn_minute;
    GX_NUMERIC_PROMPT template_mode_btn_second;
    GX_PROMPT template_mode_btn_prompt_3;
    GX_PROMPT template_mode_btn_prompt_2;
};

struct MODE_SELECT_WINDOW_CONTROL_BLOCK : public GX_WINDOW
{
    TEMPLATE_MODE_BTN_CONTROL_BLOCK mode_select_window_btn_quick;
    TEMPLATE_MODE_BTN_CONTROL_BLOCK mode_select_window_btn_deep;
    TEMPLATE_MODE_BTN_SMALL_CONTROL_BLOCK mode_select_window_btn_quick_small;
    TEMPLATE_MODE_BTN_SMALL_CONTROL_BLOCK mode_select_window_btn_deep_small;
    TEMPLATE_MODE_BTN_CONTROL_BLOCK mode_select_window_btn_eco;
    TEMPLATE_MODE_BTN_SMALL_CONTROL_BLOCK mode_select_window_btn_eco_small;
};

struct WATER_LEVEL_WINDOW_CONTROL_BLOCK : public GX_WINDOW
{
    GX_RADIAL_SLIDER water_level_window_water_level_slider;
    GX_NUMERIC_PROMPT water_level_window_water_level_value;
    GX_PROMPT water_level_window_percentage_flag;
    GX_TEXT_BUTTON water_level_window_btn_max;
    GX_TEXT_BUTTON water_level_window_btn_high;
    GX_TEXT_BUTTON water_level_window_btn_medium;
    GX_TEXT_BUTTON water_level_window_btn_low;
    GX_TEXT_BUTTON water_level_window_btn_min;
};

struct TEMPERATURE_WINDOW_CONTROL_BLOCK : public GX_WINDOW
{
    GX_RADIAL_SLIDER temperature_window_temperature_slider;
    GX_NUMERIC_PROMPT temperature_window_temperature_value;
    GX_PROMPT temperature_window_temperature_flag;
};

struct WASH_CYCLE_WINDOW_CONTROL_BLOCK : public GX_WINDOW
{
    GX_RADIAL_SLIDER wash_cycle_window_wash_cycle_slider;
    GX_NUMERIC_PROMPT wash_cycle_window_minute;
    GX_NUMERIC_PROMPT wash_cycle_window_second;
    GX_ICON wash_cycle_window_icon_1;
    GX_ICON wash_cycle_window_icon_2;
};

struct MAIN_SCREEN_CONTROL_BLOCK : public GX_WINDOW
{
    GX_ICON main_screen_logo;
    GX_BUTTON main_screen_btn_wash_cycle;
    GX_PROMPT main_screen_wash_cycle_mode;
    GX_PROMPT main_screen_wash_cycle_lable;
    GX_BUTTON main_screen_btn_temperature;
    GX_PROMPT main_screen_prompt_2;
    GX_PROMPT main_screen_temperature_lable;
    GX_NUMERIC_PROMPT main_screen_temperature_value;
    GX_BUTTON main_screen_btn_water_level;
    GX_PROMPT main_screen_prompt_4;
    GX_PROMPT main_screen_water_level_label;
    GX_NUMERIC_PROMPT main_screen_water_level_value;
    GX_PIXELMAP_BUTTON main_screen_btn_play;
    GX_PROGRESS_BAR main_screen_wash_cycle_progress_bar;
    GX_PROMPT main_screen_label_1_soak;
    GX_PROMPT main_screen_label_2_spin;
    GX_PROMPT main_screen_label_3_wash;
    GX_PROMPT main_screen_label_4_spin;
    GX_PROMPT main_screen_label_5_rinse;
    GX_PROMPT main_screen_label_6_spin;
};


/* extern statically defined control blocks                                    */

#ifndef GUIX_STUDIO_GENERATED_FILE
extern TEMPLATE_MODE_BTN_SMALL_CONTROL_BLOCK template_mode_btn_small;
extern TEMPLATE_MODE_BTN_CONTROL_BLOCK template_mode_btn;
extern MODE_SELECT_WINDOW_CONTROL_BLOCK mode_select_window;
extern WATER_LEVEL_WINDOW_CONTROL_BLOCK water_level_window;
extern TEMPERATURE_WINDOW_CONTROL_BLOCK temperature_window;
extern WASH_CYCLE_WINDOW_CONTROL_BLOCK wash_cycle_window;
extern MAIN_SCREEN_CONTROL_BLOCK main_screen;
#endif

/* Declare event process functions, draw functions, and callback functions     */

VOID time_format(GX_NUMERIC_PROMPT *, INT);
UINT mode_select_window_event_process(GX_WINDOW *widget, GX_EVENT *event_ptr);
UINT water_level_window_event_process(GX_WINDOW *widget, GX_EVENT *event_ptr);
UINT temperature_window_event_process(GX_WINDOW *widget, GX_EVENT *event_ptr);
VOID temperature_window_draw(GX_WINDOW *widget);
VOID temperature_slider_animation_callback(GX_RADIAL_SLIDER *slider);
UINT wash_cycle_window_event_process(GX_WINDOW *widget, GX_EVENT *event_ptr);
VOID wash_cycle_window_draw(GX_WINDOW *widget);
VOID wash_cycle_slider_draw(GX_RADIAL_SLIDER *widget);
UINT main_screen_event_process(GX_WINDOW *widget, GX_EVENT *event_ptr);
VOID btn_text_draw(GX_PROMPT *widget);
VOID btn_numeric_text_draw(GX_NUMERIC_PROMPT *widget);
VOID wash_cycle_progress_bar_draw(GX_PROGRESS_BAR *widget);


/* Declare Studio-generated functions for creating top-level widgets           */

UINT gx_studio_named_widget_create(char *name, GX_WIDGET *parent, GX_WIDGET **new_widget);
UINT gx_studio_display_configure(USHORT display, UINT (*driver)(GX_DISPLAY *), GX_UBYTE language, USHORT theme, GX_WINDOW_ROOT **return_root);

#endif                                       /* sentry                         */
