/***************************************************************************
 * Copyright (c) 2024 Microsoft Corporation
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * SPDX-License-Identifier: MIT
 **************************************************************************/

/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  specification file(s). For more information please refer to the Azure RTOS */
/*  GUIX Studio User Guide, or visit our web site at azure.com/rtos            */
/*                                                                             */
/*  GUIX Studio Revision 6.3.0.0 (Preview)                                     */
/*  Date (dd.mm.yyyy):  4. 9.2023   Time (hh:mm): 11:02                        */
/*******************************************************************************/


#ifndef _STANDALONE_BINRES_LOAD_16BPP_SPECIFICATIONS_H_
#define _STANDALONE_BINRES_LOAD_16BPP_SPECIFICATIONS_H_

#include "gx_studio_widget.h"

/* Define widget ids                                                           */

#define IDB_NEXT 1
#define ID_ALPHAMAP 2
#define ID_TITLE_ALPHAMAP 3
#define ID_8BIT_PALETTE 4
#define ID_TITLE_8BIT_PALETTE 5
#define ID_4444ARGB 6
#define ID_TITLE_4444ARGB 7
#define ID_565RGB 8
#define ID_TITLE_565RGB 9


/* Define animation ids                                                        */

#define GX_NEXT_ANIMATION_ID 1


/* Define user event ids                                                       */

#define GX_NEXT_USER_EVENT_ID GX_FIRST_USER_EVENT


/* Declare top-level control blocks                                            */

struct SCREEN_ALPHAMAP_CONTROL_BLOCK : public GX_WINDOW
{
    GX_TEXT_BUTTON screen_alphamap_button;
    GX_WINDOW screen_alphamap_window;
    GX_PROMPT screen_alphamap_title;
};

struct SCREEN_8BIT_PALETTE_CONTROL_BLOCK : public GX_WINDOW
{
    GX_TEXT_BUTTON screen_8bit_palette_button;
    GX_WINDOW screen_8bit_palette_window;
    GX_PROMPT screen_8bit_palette_title;
};

struct SCREEN_4444ARGB_CONTROL_BLOCK : public GX_WINDOW
{
    GX_TEXT_BUTTON screen_4444argb_button;
    GX_WINDOW screen_4444argb_window;
    GX_PROMPT screen_4444argb_title;
};

struct MAIN_SCREEN_CONTROL_BLOCK : public GX_WINDOW
{
    GX_TEXT_BUTTON main_screen_button;
    GX_WINDOW main_screen_window;
    GX_PROMPT main_screen_title;
};


/* extern statically defined control blocks                                    */

#ifndef GUIX_STUDIO_GENERATED_FILE
extern SCREEN_ALPHAMAP_CONTROL_BLOCK screen_alphamap;
extern SCREEN_8BIT_PALETTE_CONTROL_BLOCK screen_8bit_palette;
extern SCREEN_4444ARGB_CONTROL_BLOCK screen_4444argb;
extern MAIN_SCREEN_CONTROL_BLOCK main_screen;
#endif

/* Declare event process functions, draw functions, and callback functions     */

VOID pixelmap_draw(GX_WINDOW *widget);
VOID title_draw(GX_PROMPT *widget);


/* Declare Studio-generated functions for creating top-level widgets           */

UINT gx_studio_named_widget_create(char *name, GX_WIDGET *parent, GX_WIDGET **new_widget);
UINT gx_studio_display_configure(USHORT display, UINT (*driver)(GX_DISPLAY *), GX_UBYTE language, USHORT theme, GX_WINDOW_ROOT **return_root);

#endif                                       /* sentry                         */
